.big
.bp
.sy perl -e '$id="Mh_22";$id=~s/_/ /;print ".ds segment $id\\n";' > /tmp/x\n[$$]
.so /tmp/x\n[$$]
.tm Doing \*[segment]
.segm \*[segment]
.sy rm /tmp/x\n[$$]
.ds HS_START "here
.SH
.ft R
.ps +2
.vs +2
.above
.smallcaps
Medeltidshandskrift 22
./smallcaps
.below
.LP
Lund University Library
.LP
Registrum ville malmöyghe.
\fR
.LP
  The manuscript is no longer at the University Library but at the city archives of Malmö (Stadsarkivet).
