.big
.bp
.sy perl -e '$id="Mh_35";$id=~s/_/ /;print ".ds segment $id\\n";' > /tmp/x\n[$$]
.so /tmp/x\n[$$]
.tm Doing \*[segment]
.segm \*[segment]
.sy rm /tmp/x\n[$$]
.ds HS_START "here
.SH
.ft R
.ps +2
.vs +2
.above
.smallcaps
Medeltidshandskrift 35
./smallcaps
.below
.LP
Lund University Library
.br
Olim:
Bibl. Ms. H. L. a) 4:o 4; Bibl.
Meckiana N:o XIX.
.LP
\fIKaren Ludvigsdatters Tidebog.
\fR
.print-index-entry publ-place Mh_35:id2291482 .. \n[PN]
.publ-place
Denmark,
./publ-place "Denmark ... Medeltidshandskrift 35
.print-index-entry publ-date Mh_35:id2291486 .. \n[PN]
.publ-date
16th century (1500 c.),
./publ-date "16th century (1500 c.) ... 1490\(en1510 ... Medeltidshandskrift 35
.print-index-entry language Mh_35:id2291495 .. \n[PN]
.language
Danish
./language Mh_35:id2291495 ... Medeltidshandskrift 35
.LP
The prayer book of
.print-index-entry person Mh_35:id2291508 .. \n[PN]
.person
Karen Ludvigsdatter Rosenkrantz
./person Mh_35:id2291508
\& is a combination of a book of hours and a prayer book and resembles the
.print-index-entry title Mh_35:id2291518 .. \n[PN]
.title
Hortulus Animæ
./title Mh_35:id2291518###--Mh_35 --
\& type.
It contains a calendar,
.print-index-entry title Mh_35:id2291523 .. \n[PN]
.title
The Little Office of Our Lady
./title Mh_35:id2291523###--Mh_35 --
\&,
.print-index-entry title Mh_35:id2291527 .. \n[PN]
.title
The Seven Penitentiel Psalms
./title Mh_35:id2291527###--Mh_35 --
\& and a
.print-index-entry title Mh_35:id2291532 .. \n[PN]
.title
Litany of the Saints
./title Mh_35:id2291532###--Mh_35 --
\&. The Hours of the Virgin follow a redaction related to the hours (in Latin) of another Danish prayer book from around 1480 :
Ms. A 42,
Kungliga Biblioteket,
Stockholm ,
also known as
.print-index-entry title Mh_35:id2291547 .. \n[PN]
.title
\fI
.print-index-entry person Mh_35:id2291553 .. \n[PN]
.person-index "Johanne Nielsdatter Munk
Johanne Nielsdatter Munk\& s Tidebog.\fR
./title Mh_35:id2291547 ###--Mh_35 --
.
.PP
Italicized numbers in brackets refer to the numbering in the printed editions.
.\"begin msContents
.SH
.ft R
.smallcaps
Contents
./smallcaps
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1\fR 
.if !d from \{\
.ds from \*[segment] 1r
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 32v
.el .ds to \*[segment] 32v
(ff. 1r-32v)
.print-index-entry title Mh_35:id2291887 .. \n[PN]
.title
Book of Hours
./title Mh_35:id2291887###--Mh_35 1r--
\&
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.1\fR 
.if !d from \{\
.ds from \*[segment] 2r
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 6v
.el .ds to \*[segment] 6v
(ff. 2r-6v)
.print-index-entry title Mh_35:id2291908 .. \n[PN]
.title
Calendar
./title Mh_35:id2291908###--Mh_35 2r--
\& In the calendar the following local saints are mentioned:
.print-index-entry person Mh_35:id2291920 .. \n[PN]
.person
Ansgar
./person Mh_35:id2291920
\&, February 3:
ansgari ep\fIiscop\fR i ,
2v ,
.print-index-entry person Mh_35:id2291939 .. \n[PN]
.person
Knud Konge
./person Mh_35:id2291939
\& and
.print-index-entry person Mh_35:id2291945 .. \n[PN]
.person
Kjeld
./person Mh_35:id2291945
\&, July 10:
kanuti regis\fIet\fR m\fIa\fR r\fItir\fR is ketille ,
5r ,
.print-index-entry person Mh_35:id2291972 .. \n[PN]
.person
Olav
./person Mh_35:id2291972
\&, July 29:
olaui regis ,
5r ,
.print-index-entry person Mh_35:id2291986 .. \n[PN]
.person
Birgitta
./person Mh_35:id2291986
\&, October 7:
S\fIan\fR c\fIt\fR e birgitte ,
6v and
.print-index-entry person Mh_35:id2292507 .. \n[PN]
.person
Thøger
./person Mh_35:id2292507
\&, October 30:
Theodgari co\fIn\fR f\fIessoris\fR , 6v .
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2\fR 
.if !d from \{\
.ds from \*[segment] 8r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 26v
.el .ds to \*[segment] 26v
(ff. 8r:1-26v)
.print-index-entry title Mh_35:id2292546 .. \n[PN]
.title
\fIVor Frue Tider.\fR
./title Mh_35:id2292546 ###--Mh_35 8r:1--
.print-index-entry title Mh_35:id2292555 .. \n[PN]
.title
\fIOfficium Parvum Beatae Mariae Virginis.\fR
./title Mh_35:id2292555 ###--Mh_35 8r:1--
.print-index-entry title Mh_35:id2292565 .. \n[PN]
.title
\fIThe Little Office of the Blessed Virgin Mary (the Hours of the Virgin).\fR
./title Mh_35:id2292565 ###--Mh_35 8r:1--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.0\fR 
.if !d from \{\
.ds from \*[segment] 8r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 8r:16
.el .ds to \*[segment] 8r:16
(f. 8r:1-16)
.print-index-entry title Mh_35:id2292589 .. \n[PN]
.title
Praise of God the Father and the Virgin
./title Mh_35:id2292589###--Mh_35 8r:1--
\&Incipit:
\(lqHeel maria fuldh m\fIeth\fR nade\(rq Explicit:
\(lqO hellighæ iomfrw marie hedær Sywnge vi h\fIer\fR ræn loff\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1\fR 
.if !d from \{\
.ds from \*[segment] 8r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 12v:9
.el .ds to \*[segment] 12v:9
(ff. 8r:16-12v:9)
.print-index-entry title Mh_35:id2290890 .. \n[PN]
.title
\fIAd matutinum.\fR
./title Mh_35:id2290890 ###--Mh_35 8r:16--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.1\fR 
.if !d from \{\
.ds from \*[segment] 8r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 8v:16
.el .ds to \*[segment] 8v:16
(f. 8r:16-8v:16)
.print-index-entry title Mh_35:id2290914 .. \n[PN]
.title
\fIPsalmus 95 (94): Venite,
exultemus Domino.\fR
./title Mh_35:id2290914 ###--Mh_35 8r:16--
Rubric:
\(lqvenite\(rq Incipit:
\(lqKom\fIm\fR ær,
vi gledhæ os i h\fIer\fR ræn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.2\fR 
.if !d from \{\
.ds from \*[segment] 8v:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 9r:15
.el .ds to \*[segment] 9r:15
(ff. 8v:16-9r:15)
.print-index-entry title Mh_35:id2290955 .. \n[PN]
.title
\fIHymnus.
Quem terra,
pontus,
ethera.\fR
./title Mh_35:id2290955 ###--Mh_35 8v:16--
Rubric:
\(lqympn\fIus\fR\(rq Incipit:
\(lqIomfrw marie liiff baar th\fIe\fR n ther iorde\fIn\fR hauer och hi\fIm\fR melen dyrkæ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.3\fR 
.if !d from \{\
.ds from \*[segment] 9r:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 9v:12
.el .ds to \*[segment] 9v:12
(f. 9r:15-9v:12)
.print-index-entry title Mh_35:id2291007 .. \n[PN]
.title
\fIPsalmus 8:
Domine,
Dominus noster.\fR
./title Mh_35:id2291007 ###--Mh_35 9r:15--
Rubric:
\(lqd\fIomi\fR ne d\fIomi\fR n\fIu\fR s n\fIoste\fR r\(rq Incipit:
\(lqH\fIer\fR ræ vor h\fIer\fR ræ huræ vndærlig ær thit naffn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.4\fR 
.if !d from \{\
.ds from \*[segment] 9v:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 10r:22
.el .ds to \*[segment] 10r:22
(ff. 9v:16-10r:22)
.print-index-entry title Mh_35:id2291066 .. \n[PN]
.title
\fIPsalmus 19 (18): Caeli enarrent gloriam Dei.\fR
./title Mh_35:id2291066 ###--Mh_35 9v:16--
Incipit:
\(lqHimlæne ku\fIn\fR giøre gusz ære\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.5\fR 
.if !d from \{\
.ds from \*[segment] 10r:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 10v:23
.el .ds to \*[segment] 10v:23
(f. 10r:23-10v:23)
.print-index-entry title Mh_35:id2291100 .. \n[PN]
.title
\fIPsalmus 24 (23): Domini est terra et plenitudo eius.\fR
./title Mh_35:id2291100 ###--Mh_35 10r:23--
Incipit:
\(lqHerre\fIn\fR s ær iorde\fIn\fR och henne fule iørderigh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.6\fR 
.if !d from \{\
.ds from \*[segment] 10v:24
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 11r:5
.el .ds to \*[segment] 11r:5
(ff. 10v:24-11r:5)
.print-index-entry title Mh_35:id2291138 .. \n[PN]
.title
\fIAbsolutio.
Precibus et meritis.\fR
./title Mh_35:id2291138 ###--Mh_35 10v:24--
Incipit:
\(lqThu all mektugæste fadær mildh och miskundh h\fIer\fR ræ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.7\fR 
.if !d from \{\
.ds from \*[segment] 11r:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 11r:19
.el .ds to \*[segment] 11r:19
(f. 11r:5-19)
.print-index-entry title Mh_35:id2291173 .. \n[PN]
.title
\fILectio prima.
Sancta maria virgo.\fR
./title Mh_35:id2291173 ###--Mh_35 11r:5--
Rubric:
\(lqleccio\(rq Incipit:
\(lqS\fIan\fR c\fIt\fR a maria,
iomfrw ouer alle i\fIom\fR fruær\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.8\fR 
.if !d from \{\
.ds from \*[segment] 11r:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 11v:6
.el .ds to \*[segment] 11v:6
(f. 11r:19-11v:6)
.print-index-entry title Mh_35:id2291218 .. \n[PN]
.title
\fILectio secunda.
Sancta maria piarum.\fR
./title Mh_35:id2291218 ###--Mh_35 11r:19--
Rubric:
\(lqleccio\(rq Incipit:
\(lqS\fIan\fR c\fIt\fR a ma\fIri\fR a, mildæstæ ouer alle milde och helligæstæ ouer alle hellige\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.9\fR 
.if !d from \{\
.ds from \*[segment] 11v:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 11v:20
.el .ds to \*[segment] 11v:20
(f. 11v:7-20)
.print-index-entry title Mh_35:id2291268 .. \n[PN]
.title
\fILectio tertia.
Sancta dei genetrix.\fR
./title Mh_35:id2291268 ###--Mh_35 11v:7--
Incipit:
\(lqHellighæ gusz modær thu so\fIm\fR værduge var ath vntfonghæ the\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.1.10\fR 
.if !d from \{\
.ds from \*[segment] 11v:21
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 12v:9
.el .ds to \*[segment] 12v:9
(ff. 11v:21-12v:9)
.print-index-entry title Mh_35:id2291306 .. \n[PN]
.title
\fIHymnus sanctorum Ambrosii et Augustini.
Te deum.\fR
./title Mh_35:id2291306 ###--Mh_35 11v:21--
Incipit:
\(lqVi loue thik,
vi ki\fIn\fR ne thic til h\fIer\fR ræ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2\fR 
.if !d from \{\
.ds from \*[segment] 12v:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 16v:23
.el .ds to \*[segment] 16v:23
(ff. 12v:10-16v:23)
.print-index-entry title Mh_35:id2291345 .. \n[PN]
.title
\fIAd laudes.\fR
./title Mh_35:id2291345 ###--Mh_35 12v:10--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.1\fR 
.if !d from \{\
.ds from \*[segment] 12v:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 12v:22
.el .ds to \*[segment] 12v:22
(f. 12v:10-22)
.print-index-entry title Mh_35:id2291368 .. \n[PN]
.title
\fIPsalmus 93 (92): Dominus regnavit!.\fR
./title Mh_35:id2291368 ###--Mh_35 12v:10--
Incipit:
\(lqHerræ regnerdæ och in førdæ fauerligh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.2\fR 
.if !d from \{\
.ds from \*[segment] 12v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 13r:8
.el .ds to \*[segment] 13r:8
(ff. 12v:23-13r:8)
.print-index-entry title Mh_35:id2289940 .. \n[PN]
.title
\fIPsalmus 100 (99): Iubilate Domino,
omnis terra.\fR
./title Mh_35:id2289940 ###--Mh_35 12v:23--
Incipit:
\(lqSyungær gusz loff allæ iørdærigi\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.3\fR 
.if !d from \{\
.ds from \*[segment] 13r:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 13v:9
.el .ds to \*[segment] 13v:9
(f. 13r:9-13v:9)
.print-index-entry title Mh_35:id2289968 .. \n[PN]
.title
\fIPsalmus 63 (62): Deus,
deus meus es tu.\fR
./title Mh_35:id2289968 ###--Mh_35 13r:9--
Incipit:
\(lqGvdh myn gudh iæch vagær til thik aff lyuset\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.4\fR 
.if !d from \{\
.ds from \*[segment] 13v:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 13v:21
.el .ds to \*[segment] 13v:21
(f. 13v:9-21)
.print-index-entry title Mh_35:id2289996 .. \n[PN]
.title
\fIPsalmus 67 (66): Deus misereatur nostri.\fR
./title Mh_35:id2289996 ###--Mh_35 13v:9--
Incipit:
\(lqGudh misku\fIn\fR dæ os och velsigne os han for lyusæ sit anlædæ ouer os och miskunde os\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.5\fR 
.if !d from \{\
.ds from \*[segment] 13v:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 14v:7
.el .ds to \*[segment] 14v:7
(ff. 13v-14v:7)
.print-index-entry title Mh_35:id2290029 .. \n[PN]
.title
\fICanticum trium puerorum.
Benedicite.\fR
./title Mh_35:id2290029 ###--Mh_35 13v:22--
Incipit:
\(lqVelsigne h\fIer\fR ræn alle h\fIer\fR rens giærnin\fIn\fR ger\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.6\fR 
.if !d from \{\
.ds from \*[segment] 14v:8
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 15v:10
.el .ds to \*[segment] 15v:10
(ff. 14v:8-15v:10)
.print-index-entry title Mh_35:id2290068 .. \n[PN]
.title
\fIPsalmus 148:
Alleluia.
Laudate Dominum de caelis.\fR
./title Mh_35:id2290068 ###--Mh_35 14v:8--
Incipit:
\(lqLoffuær h\fIer\fR ræn aff hi\fIm\fR melæne\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.7\fR 
.if !d from \{\
.ds from \*[segment] 15v:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 15v:15
.el .ds to \*[segment] 15v:15
(f. 15v:10-15)
.print-index-entry title Mh_35:id2290104 .. \n[PN]
.title
\fICapitulum.
In omnibus requiem quesiui.\fR
./title Mh_35:id2290104 ###--Mh_35 15v:10--
Rubric:
\(lqca\fIpitulu\fR m\(rq Incipit:
\(lqI alle the thingh lettæ iæch æfftær roo\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.8\fR 
.if !d from \{\
.ds from \*[segment] 15v:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 16r:5
.el .ds to \*[segment] 16r:5
(ff. 15v:15-16r:5)
.print-index-entry title Mh_35:id2290140 .. \n[PN]
.title
\fIHymnus:
O gloriosa domina.\fR
./title Mh_35:id2290140 ###--Mh_35 15v:15--
Rubric:
\(lqym\fInus\fR\(rq Incipit:
\(lqO ære fulle fruæ opp høgdh ouer stiærnere\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.9\fR 
.if !d from \{\
.ds from \*[segment] 16r:6
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 16v:9
.el .ds to \*[segment] 16v:9
(f. 16r:6-16v:9)
.print-index-entry title Mh_35:id2290174 .. \n[PN]
.title
\fICanticum Zacharie prophete.
Benedictus dominus.\fR
./title Mh_35:id2290174 ###--Mh_35 16r:6--
Incipit:
\(lqVælsign\fIet\fR være h\fIer\fR ræn israhels gudh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.2.10\fR 
.if !d from \{\
.ds from \*[segment] 16v:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 16v:23
.el .ds to \*[segment] 16v:23
(f. 16v:10-23)
.print-index-entry title Mh_35:id2290210 .. \n[PN]
.title
\fICollecta.
Concede nos.\fR
./title Mh_35:id2290210 ###--Mh_35 16v:10--
Incipit:
\(lqVi bedhæ thic vor h\fIer\fR ræ gudh giff os thine tiener ath gledes\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3\fR 
.if !d from \{\
.ds from \*[segment] 16v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 18r:22
.el .ds to \*[segment] 18r:22
(ff. 16v:23-18r:22)
.print-index-entry title Mh_35:id2290244 .. \n[PN]
.title
\fIAd primam.\fR
./title Mh_35:id2290244 ###--Mh_35 16v:23--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3.1\fR 
.if !d from \{\
.ds from \*[segment] 16v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 17r:5
.el .ds to \*[segment] 17r:5
(ff. 16v:23-17r:5)
.print-index-entry title Mh_35:id2290267 .. \n[PN]
.title
\fIHymnus.
Rex christe clementissime.\fR
./title Mh_35:id2290267 ###--Mh_35 16v:23--
Rubric:
\(lqympn\fIus\fR\(rq Incipit:
\(lqO christe,
mildistæ ko\fIn\fR nigh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3.2\fR 
.if !d from \{\
.ds from \*[segment] 17r:6
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 17r:17
.el .ds to \*[segment] 17r:17
(f. 17r:6-17)
.print-index-entry title Mh_35:id2290305 .. \n[PN]
.title
\fIPsalmus 120 (119): Ad Dominum,
cum tribularer.\fR
./title Mh_35:id2290305 ###--Mh_35 17r:6--
Incipit:
\(lqThe\fIn\fR tidh iæch roptæ til h\fIer\fR ræn och var bedrøuet\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3.3\fR 
.if !d from \{\
.ds from \*[segment] 17r:18
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 17v:6
.el .ds to \*[segment] 17v:6
(f. 17r:18-17v:6)
.print-index-entry title Mh_35:id2290341 .. \n[PN]
.title
\fIPsalmus 121 (120): Levabo ocolos meos in montes.\fR
./title Mh_35:id2290341 ###--Mh_35 17r:18--
Incipit:
\(lqIæch loffuedhæ myne øuen opp til biergæne\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3.4\fR 
.if !d from \{\
.ds from \*[segment] 17v:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 17v:23
.el .ds to \*[segment] 17v:23
(f. 17v:7-23)
.print-index-entry title Mh_35:id2290373 .. \n[PN]
.title
\fIPsalmus 122 (121): Laetatus sum in eo.\fR
./title Mh_35:id2290373 ###--Mh_35 17v:7--
Incipit:
\(lqIæch ær gladh vorden i the thingh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3.5\fR 
.if !d from \{\
.ds from \*[segment] 17v:24
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 18r:13
.el .ds to \*[segment] 18r:13
(ff. 17v:24-18r:13)
.print-index-entry title Mh_35:id2290401 .. \n[PN]
.title
\fICapitulum.
Haec est virgo.\fR
./title Mh_35:id2290401 ###--Mh_35 17v:24--
Incipit:
\(lqThi\fIn\fR ne iamfru ær helligh och ære fuldh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.3.6\fR 
.if !d from \{\
.ds from \*[segment] 18r:14
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 18r:22
.el .ds to \*[segment] 18r:22
(f. 18r:14-22)
.print-index-entry title Mh_35:id2290433 .. \n[PN]
.title
\fICollecta.
Sancta maria.\fR
./title Mh_35:id2290433 ###--Mh_35 18r:14--
Incipit:
\(lqS\fIan\fR c\fIt\fR a maria,
vor h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR i modær\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4\fR 
.if !d from \{\
.ds from \*[segment] 18r:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 19v:
.el .ds to \*[segment] 19v:
(ff. 18r-19v)
.print-index-entry title Mh_35:id2290481 .. \n[PN]
.title
\fIAd tertiam.\fR
./title Mh_35:id2290481 ###--Mh_35 18r:22--
Rubric:
\(lqad t\fIertiam\fR\(rq
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4.1\fR 
.if !d from \{\
.ds from \*[segment] 18r:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 18r:24
.el .ds to \*[segment] 18r:24
(f. 18r:23-24)
.print-index-entry title Mh_35:id2290511 .. \n[PN]
.title
\fIHymnus:
Rex Christe.\fR
./title Mh_35:id2290511 ###--Mh_35 18r:23--
Rubric:
\(lqym\fInus\fR\(rq Incipit:
\(lqO\fIchrist\fR e misku\fIn\fR deligste konige so\fIm\fR i prim staar\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4.2\fR 
.if !d from \{\
.ds from \*[segment] 18r:25
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 18v:10
.el .ds to \*[segment] 18v:10
(f. 18r:25-18v:10)
.print-index-entry title Mh_35:id2290556 .. \n[PN]
.title
\fIPsalmus 123 (122): Ad te lavavi oculos meos.\fR
./title Mh_35:id2290556 ###--Mh_35 18r:25--
Incipit:
\(lqIech løfftæ myne øuen opp til tik\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4.3\fR 
.if !d from \{\
.ds from \*[segment] 18v:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 18v:26
.el .ds to \*[segment] 18v:26
(f. 18v:11-26)
.print-index-entry title Mh_35:id2290584 .. \n[PN]
.title
\fIPsalmus 124 (123): Nisi quia Dominus erat in nobis.\fR
./title Mh_35:id2290584 ###--Mh_35 18v:11--
Rubric:
\(lqpsalm\fIus\fR\(rq Incipit:
\(lqForty vden h\fIer\fR ræn hauer været i os\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4.4\fR 
.if !d from \{\
.ds from \*[segment] 19r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 19r:15
.el .ds to \*[segment] 19r:15
(f. 19r:1-15)
.print-index-entry title Mh_35:id2290622 .. \n[PN]
.title
\fIPsalmus 125 (124): Qui confidunt in Domino.\fR
./title Mh_35:id2290622 ###--Mh_35 19r:1--
Incipit:
\(lqThe ther trøste paa h\fIer\fR ræn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4.5\fR 
.if !d from \{\
.ds from \*[segment] 19r:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 19r:25
.el .ds to \*[segment] 19r:25
(f. 19r:15-25)
.print-index-entry title Mh_35:id2290654 .. \n[PN]
.title
\fIAb initio et ante secula creata sum.\fR
./title Mh_35:id2290654 ###--Mh_35 19r:15--
Rubric:
\(lqcapitulu\fIm\fR\(rq Incipit:
\(lqAff opp hoff och for værde\fIn\fR ær <iæch> skapt\(rq Explicit:
\(lqH\fIer\fR re,
hør myn bøn\(rq cf.
Ecclesiasticus 24.14
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.4.6\fR 
.if !d from \{\
.ds from \*[segment] 19v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 19v:11
.el .ds to \*[segment] 19v:11
(f. 19v:1-11)
.print-index-entry title Mh_35:id2290711 .. \n[PN]
.title
\fICollecta.
Deus qui de beate marie.\fR
./title Mh_35:id2290711 ###--Mh_35 19v:1--
Incipit:
\(lqGudh thu som vilde ath thit ordh skullæ tagæ kiødh aff iomfrw maria liiff\(rq Explicit:
\(lqOch vel signæ vi h\fIer\fR ræn Gudh være tak\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.5\fR 
.if !d from \{\
.ds from \*[segment] 19v:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 20v:25
.el .ds to \*[segment] 20v:25
(ff. 19v:12-20v:25)
.print-index-entry title Mh_35:id2290751 .. \n[PN]
.title
\fIAd sextam.\fR
./title Mh_35:id2290751 ###--Mh_35 19v:12--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.5.1\fR 
.if !d from \{\
.ds from \*[segment] 19v:13
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 19v:25
.el .ds to \*[segment] 19v:25
(f. 19v:13-25)
.print-index-entry title Mh_35:id2290774 .. \n[PN]
.title
\fIPsalmus 126 (125): In convertendo captivitatem Sion.\fR
./title Mh_35:id2290774 ###--Mh_35 19v:13--
Incipit:
\(lqThe\fIn\fR tidh h\fIer\fR ræn vændhæ syons fængxæl\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.5.2\fR 
.if !d from \{\
.ds from \*[segment] 20r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 20r:15
.el .ds to \*[segment] 20r:15
(f. 20r:1-15)
.print-index-entry title Mh_35:id2290810 .. \n[PN]
.title
\fIPsalmus 127 (126): Nisi Dominus aedificaverit domum.\fR
./title Mh_35:id2290810 ###--Mh_35 20r:1--
Incipit:
\(lqUdhen h\fIer\fR ræn byggæde huss\fIet\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.5.3\fR 
.if !d from \{\
.ds from \*[segment] 20r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 20v:5
.el .ds to \*[segment] 20v:5
(f. 20r:16-20v:5)
.print-index-entry title Mh_35:id2290844 .. \n[PN]
.title
\fIPsalmus 128 (127): Beati omnes.\fR
./title Mh_35:id2290844 ###--Mh_35 20r:16--
Incipit:
\(lqHelligh ære alle the som rædes h\fIer\fR ræn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.5.4\fR 
.if !d from \{\
.ds from \*[segment] 20v:6
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 20v:14
.el .ds to \*[segment] 20v:14
(f. 20v:6-14)
.print-index-entry title Mh_35:id2290876 .. \n[PN]
.title
\fICapitulum.
Et sic in Sion firmata sum.\fR
./title Mh_35:id2290876 ###--Mh_35 20v:6--
Incipit:
\(lqOch sa ær iech fast giordh i syon\(rq cf.
Ecclesiasticus 24.15
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.5.5\fR 
.if !d from \{\
.ds from \*[segment] 20v:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 20v:25
.el .ds to \*[segment] 20v:25
(f. 20v:15-25)
.print-index-entry title Mh_35:id2292652 .. \n[PN]
.title
\fICollecta.
Deus qui salutis.\fR
./title Mh_35:id2292652 ###--Mh_35 20v:15--
Incipit:
\(lqGudh thu so\fIm\fR gaffst me\fIn\fR niskens slekt ewi\fIn\fR eligh slekt ewi\fIn\fR eligh hielsens løn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6\fR 
.if !d from \{\
.ds from \*[segment] 21r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 22r:6
.el .ds to \*[segment] 22r:6
(ff. 21r:1-22r:6)
.print-index-entry title Mh_35:id2292700 .. \n[PN]
.title
\fIAd nonam.\fR
./title Mh_35:id2292700 ###--Mh_35 21r:1--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6.1\fR 
.if !d from \{\
.ds from \*[segment] 21r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 21r:1
.el .ds to \*[segment] 21r:1
(f. 21r:1)
.print-index-entry title Mh_35:id2292724 .. \n[PN]
.title
\fIHymnus.
Rex christe clementissime.\fR
./title Mh_35:id2292724 ###--Mh_35 21r:1--
Incipit:
\(lqO\fIchrist\fR e, mildiste ko\fIn\fR nigh,
giør vor hiær<tæ>\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6.2\fR 
.if !d from \{\
.ds from \*[segment] 21r:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 21r:15
.el .ds to \*[segment] 21r:15
(f. 21r:2-15)
.print-index-entry title Mh_35:id2292764 .. \n[PN]
.title
\fIPsalmus 129 (128): Saepe expugnaverunt me a iuventute mea.\fR
./title Mh_35:id2292764 ###--Mh_35 21r:2--
Incipit:
\(lqThe haue offtæ bestridh mik aff mynæ vngdom\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6.3\fR 
.if !d from \{\
.ds from \*[segment] 21r:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 21v:1
.el .ds to \*[segment] 21v:1
(f. 21r:15-21v:1)
.print-index-entry title Mh_35:id2292792 .. \n[PN]
.title
\fIPsalmus 130 (129): De profundis clamavi ad te,
Domine.\fR
./title Mh_35:id2292792 ###--Mh_35 21r:15--
Rubric:
\(lqpsalm\fIus\fR\(rq Incipit:
\(lqAff dyubæ roptæ iæch til h\fIer\fR ren h\fIer\fR ræ høør myn bøn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6.4\fR 
.if !d from \{\
.ds from \*[segment] 21v:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 21v:13
.el .ds to \*[segment] 21v:13
(f. 21v:2-13)
.print-index-entry title Mh_35:id2292835 .. \n[PN]
.title
\fIPsalmus 131 (130): Domine,
non est exaltatum cor meum.\fR
./title Mh_35:id2292835 ###--Mh_35 21v:2--
Incipit:
\(lqH\fIer\fR ræ,
mith hiærtæ ær ey opp høgh\fIet\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6.5\fR 
.if !d from \{\
.ds from \*[segment] 21v:13
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 21v:22
.el .ds to \*[segment] 21v:22
(f. 21v:13-22)
.print-index-entry title Mh_35:id2292870 .. \n[PN]
.title
\fICapitulum.
Et radicavi in populo honorificatu.\fR
./title Mh_35:id2292870 ###--Mh_35 21v:13--
Rubric:
\(lqca\fIpitulu\fR m\(rq Incipit:
\(lqOch iæch hauer fæst myne rodh i th\fIet\fR hedrædæ folk\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.6.6\fR 
.if !d from \{\
.ds from \*[segment] 21v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 22r:6
.el .ds to \*[segment] 22r:6
(ff. 21v:23-22r:6)
.print-index-entry title Mh_35:id2292917 .. \n[PN]
.title
\fICollecta.
Concede misericors deus.\fR
./title Mh_35:id2292917 ###--Mh_35 21v:23--
Incipit:
\(lqMisku\fIn\fR dæ gudh giff vor skrøbelighet hielp och styrkiæ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7\fR 
.if !d from \{\
.ds from \*[segment] 22r:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 24r
.el .ds to \*[segment] 24r
(ff. 22r:7-24r:24)
.print-index-entry title Mh_35:id2292950 .. \n[PN]
.title
\fIAd vesperas.\fR
./title Mh_35:id2292950 ###--Mh_35 22r:7--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.1\fR 
.if !d from \{\
.ds from \*[segment] 22r:8
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 22v:4
.el .ds to \*[segment] 22v:4
(f. 22r:8-22v:4)
.print-index-entry title Mh_35:id2292974 .. \n[PN]
.title
\fIPsalmus 110 (109): Dixit Dominus Domino meo.\fR
./title Mh_35:id2292974 ###--Mh_35 22r:8--
Incipit:
\(lqH\fIer\fR ræn saudhe til my\fIn\fR h\fIer\fR ræ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.2\fR 
.if !d from \{\
.ds from \*[segment] 22v:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 22v:19
.el .ds to \*[segment] 22v:19
(f. 22v:5-19)
.print-index-entry title Mh_35:id2293013 .. \n[PN]
.title
\fIPsalmus 113 (112): Laudate,
pueri Dominum.\fR
./title Mh_35:id2293013 ###--Mh_35 22v:5--
Incipit:
\(lqLoffuær h\fIer\fR ræn i børn loffuer h\fIer\fR ræns naff\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.3\fR 
.if !d from \{\
.ds from \*[segment] 22v:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 22v:22
.el .ds to \*[segment] 22v:22
(f. 22v:19-22)
.print-index-entry title Mh_35:id2293052 .. \n[PN]
.title
\fIPsalmus 122 (121): Laetatus sum in his quae dicta sunt mihi.\fR
./title Mh_35:id2293052 ###--Mh_35 22v:19--
Incipit:
\(lqIæch ær gladh vorde\fIn\fR i the thingh ther mik ær saud\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.4\fR 
.if !d from \{\
.ds from \*[segment] 22v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 22v:24
.el .ds to \*[segment] 22v:24
(f. 22v:23-24)
.print-index-entry title Mh_35:id2293084 .. \n[PN]
.title
\fIPsalmus 127 (126): Nisi Dominus aedeficaverit domum.\fR
./title Mh_35:id2293084 ###--Mh_35 22v:23--
Incipit:
\(lqUdhen h\fIer\fR ræn byggær hus\fIet\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.5\fR 
.if !d from \{\
.ds from \*[segment] 22v:25
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 23r:18
.el .ds to \*[segment] 23r:18
(ff. 22v:25-23r:18)
.print-index-entry title Mh_35:id2293118 .. \n[PN]
.title
\fIPsalmus 147:
Lauda Ierusalem,
Dominum.\fR
./title Mh_35:id2293118 ###--Mh_35 22v:25--
Incipit:
\(lqIh\fIerusa\fR l\fIe\fR m loffue thin h\fIer\fR re\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.6\fR 
.if !d from \{\
.ds from \*[segment] 23r:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 23v:2
.el .ds to \*[segment] 23v:2
(f. 23r:19-23v)
.print-index-entry title Mh_35:id2293157 .. \n[PN]
.title
\fICapitulum.
Beata es,
virgo maria.\fR
./title Mh_35:id2293157 ###--Mh_35 23r:19--
Incipit:
\(lqHelligh æst thu iomfrw maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.7\fR 
.if !d from \{\
.ds from \*[segment] 23v:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 23v:21
.el .ds to \*[segment] 23v:21
(f. 23v:2-21)
.print-index-entry title Mh_35:id2293184 .. \n[PN]
.title
\fIHymnus.
Ave maris stella.\fR
./title Mh_35:id2293184 ###--Mh_35 23v:2--
Incipit:
\(lqHeel haffzæns stiærne hellighe gusz modær\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.8\fR 
.if !d from \{\
.ds from \*[segment] 23v:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 24r:20
.el .ds to \*[segment] 24r:20
(ff. 23v:22-24r:20)
.print-index-entry title Mh_35:id2293212 .. \n[PN]
.title
\fICanticum beatae mariae virginis.
Magnificat.\fR
./title Mh_35:id2293212 ###--Mh_35 23v:22--
Incipit:
\(lqMin siæl loffuær h\fIer\fR ræn och myn andh hauer fryd\fIet\fR sik\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.7.9\fR 
.if !d from \{\
.ds from \*[segment] 24r:21
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 24r:24
.el .ds to \*[segment] 24r:24
(f. 24r:21-24)
.print-index-entry title Mh_35:id2293248 .. \n[PN]
.title
\fICollecta.
Concede nos.\fR
./title Mh_35:id2293248 ###--Mh_35 24r:21--
Incipit:
\(lqVi bede thic vor h\fIer\fR ræ gudh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8\fR 
.if !d from \{\
.ds from \*[segment] 24v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 26r:15
.el .ds to \*[segment] 26r:15
(ff. 24v:1-26r:15)
.print-index-entry title Mh_35:id2293281 .. \n[PN]
.title
\fIAd completorium.\fR
./title Mh_35:id2293281 ###--Mh_35 24v:1--
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.1\fR 
.if !d from \{\
.ds from \*[segment] 24v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 25r:11
.el .ds to \*[segment] 25r:11
(ff. 24v:1-25r:11)
.print-index-entry title Mh_35:id2293304 .. \n[PN]
.title
\fIPsalmus 132 (131): Memento,
Domine,
David.\fR
./title Mh_35:id2293304 ###--Mh_35 24v:1--
Incipit:
\(lqH\fIer\fR ræ my\fIn\fR nes dauid\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.2\fR 
.if !d from \{\
.ds from \*[segment] 25r:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 25r:18
.el .ds to \*[segment] 25r:18
(f. 25r:12-18)
.print-index-entry title Mh_35:id2293339 .. \n[PN]
.title
\fIPsalmus 133 (132): Ecce quam bonum et quam iucundum.\fR
./title Mh_35:id2293339 ###--Mh_35 25r:12--
Incipit:
\(lqSee hure goth och hure frygdeligh th\fIet\fR ær\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.3\fR 
.if !d from \{\
.ds from \*[segment] 25r:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 25v:2
.el .ds to \*[segment] 25v:2
(f. 25r:19-25v:2)
.print-index-entry title Mh_35:id2293371 .. \n[PN]
.title
\fIPsalmus 134 (133): Ecce nunc benedicite Dominum.\fR
./title Mh_35:id2293371 ###--Mh_35 25r:19--
Incipit:
\(lqSee vælsigner nw h\fIer\fR ræn alle h\fIer\fR rens sue\fIn\fR ne\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.4\fR 
.if !d from \{\
.ds from \*[segment] 25v:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 25v:9
.el .ds to \*[segment] 25v:9
(f. 25v:3-9)
.print-index-entry title Mh_35:id2293410 .. \n[PN]
.title
\fICapitulum.
Multe filie.\fR
./title Mh_35:id2293410 ###--Mh_35 25v:3--
Incipit:
\(lqManghæ døttræ same\fIn\fR sanckædæ rigdo\fIm\fR me\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.5\fR 
.if !d from \{\
.ds from \*[segment] 25v:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 25v:19
.el .ds to \*[segment] 25v:19
(f. 25v:10-19)
.print-index-entry title Mh_35:id2293446 .. \n[PN]
.title
\fIHymnus.
Fit porta christi.\fR
./title Mh_35:id2293446 ###--Mh_35 25v:10--
Incipit:
\(lqChristi porth ær opp laden och opp fylt\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.6\fR 
.if !d from \{\
.ds from \*[segment] 25v:20
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 26r:7
.el .ds to \*[segment] 26r:7
(ff. 25v:20-26r:7)
.print-index-entry title Mh_35:id2293473 .. \n[PN]
.title
\fICanticum Simeonis.
Nunc dimittis.\fR
./title Mh_35:id2293473 ###--Mh_35 25v:20--
Incipit:
\(lqH\fIer\fR ræ,
ladh nw thin suendh i fredh æfft\fIer\fR thit ordh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.2.8.7\fR 
.if !d from \{\
.ds from \*[segment] 26r:8
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 26r:15
.el .ds to \*[segment] 26r:15
(f. 26r:8-15)
.print-index-entry title Mh_35:id2293509 .. \n[PN]
.title
\fICollecta.
Famulorum tuorum.\fR
./title Mh_35:id2293509 ###--Mh_35 26r:8--
Incipit:
\(lqH\fIer\fR ræ,
vi bedhæ thic,
for ladh thine tieners syndær\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3\fR 
.if !d from \{\
.ds from \*[segment] 26r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 30v
.el .ds to \*[segment] 30v
(ff. 26r:16-30v:20)
.print-index-entry title Mh_35:id2293544 .. \n[PN]
.title
\fIDe Syv Bodssalmer.\fR
./title Mh_35:id2293544 ###--Mh_35 26r:16--
.print-index-entry title Mh_35:id2293553 .. \n[PN]
.title
\fISeptem Psalmi Penitenciales.\fR
./title Mh_35:id2293553 ###--Mh_35 26r:16--
.print-index-entry title Mh_35:id2293562 .. \n[PN]
.title
\fIThe Seven Penitential Psalms.\fR
./title Mh_35:id2293562 ###--Mh_35 26r:16--
Rubric:
\(lqSyw salme pa da\fIn\fR ske\(rq
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.1\fR 
.if !d from \{\
.ds from \*[segment] 26r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 26v:14
.el .ds to \*[segment] 26v:14
(f. 26r:16-26v:14)
.print-index-entry title Mh_35:id2293594 .. \n[PN]
.title
\fIPsalmus 6:
Domine,
ne in furore tuo argas me.\fR
./title Mh_35:id2293594 ###--Mh_35 26r:16--
Incipit:
\(lqH\fIer\fR ræ straffe mik ey i thin brædhæ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.2\fR 
.if !d from \{\
.ds from \*[segment] 26v:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 27r:17
.el .ds to \*[segment] 27r:17
(ff. 26v:15-27r:17)
.print-index-entry title Mh_35:id2293626 .. \n[PN]
.title
\fIPsalmus 32 (31): Beatus,
cui remissa est inquitas.\fR
./title Mh_35:id2293626 ###--Mh_35 26v:15--
Incipit:
\(lqHelligh ære the thieres vndskab ære for ladænæ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.3\fR 
.if !d from \{\
.ds from \*[segment] 27r:18
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 28r:14
.el .ds to \*[segment] 28r:14
(ff. 27r:18-28r:14)
.print-index-entry title Mh_35:id2293655 .. \n[PN]
.title
\fIPsalmus 38 (37): Domine,
ne in furore tuo argas me.\fR
./title Mh_35:id2293655 ###--Mh_35 27r:18--
Incipit:
\(lqH\fIer\fR ræ straffe mik ey i thin brædhæ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.4\fR 
.if !d from \{\
.ds from \*[segment] 28r:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 29r:4
.el .ds to \*[segment] 29r:4
(ff. 28r:15-29r:4)
.print-index-entry title Mh_35:id2293687 .. \n[PN]
.title
\fIPsalmus 51 (50): Miserere mei,
Deus.\fR
./title Mh_35:id2293687 ###--Mh_35 28r:15--
Incipit:
\(lqMisku\fIn\fR dæ mik,
gudh for thin storæ miskwndh\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.5\fR 
.if !d from \{\
.ds from \*[segment] 29r:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 30r:9
.el .ds to \*[segment] 30r:9
(ff. 29r:5-30r:9)
.print-index-entry title Mh_35:id2293719 .. \n[PN]
.title
\fIPsalmus 102 (102): Domine,
exaudi orationem.\fR
./title Mh_35:id2293719 ###--Mh_35 29r:5--
Incipit:
\(lqH\fIer\fR ræ,
høør myn bøn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.6\fR 
.if !d from \{\
.ds from \*[segment] 30r:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 30r:11
.el .ds to \*[segment] 30r:11
(f. 30r:10-11)
.print-index-entry title Mh_35:id2293750 .. \n[PN]
.title
\fIPsalmus 130 (129): De profundis clamavi ad te,
domine.\fR
./title Mh_35:id2293750 ###--Mh_35 30r:10--
Incipit:
\(lqAff dyub roptæ iæch til thic herre\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.3.7\fR 
.if !d from \{\
.ds from \*[segment] 30r:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 30v:20
.el .ds to \*[segment] 30v:20
(f. 30r:12-30v:20)
.print-index-entry title Mh_35:id2293778 .. \n[PN]
.title
\fIPsalmus 143 (142): Domine,
exaudi orationem meam.\fR
./title Mh_35:id2293778 ###--Mh_35 30r:12--
Incipit:
\(lqH\fIer\fR ræ høør my\fIn\fR bøn\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB1.4\fR 
.if !d from \{\
.ds from \*[segment] 30v:21
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 32v:18
.el .ds to \*[segment] 32v:18
(ff. 31r-32v:18)
.print-index-entry title Mh_35:id2293815 .. \n[PN]
.title
\fIAllehelgenslitaniet.\fR
./title Mh_35:id2293815 ###--Mh_35 30v:21--
.print-index-entry title Mh_35:id2293824 .. \n[PN]
.title
\fIThe Litany of the Saints.\fR
./title Mh_35:id2293824 ###--Mh_35 30v:21--
Incipit:
\(lqKyriel\fIeison\fR\fIChrist\fR eleyso\fIn\fR\(rq Explicit:
\(lqoch ladh mik see the\fIm\fR i hi\fIm\fR mærigis rigi och th\fIe\fR r ewi\fIn\fR nelig at leue Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2\fR 
.if !d from \{\
.ds from \*[segment] 33r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 110v
.el .ds to \*[segment] 110v
(ff. 33r:1-110v)
.print-index-entry title Mh_35:id2293889 .. \n[PN]
.title
Prayer book
./title Mh_35:id2293889###--Mh_35 33r:1--
\&
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1\fR 
.if !d from \{\
.ds from \*[segment] 33r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 64v:23
.el .ds to \*[segment] 64v:23
(ff. 33r:1-64v:23)
.print-index-entry title Mh_35:id2293910 .. \n[PN]
.title
Prayers to Our Lord Jesus Christ and to the Trinity
./title Mh_35:id2293910###--Mh_35 33r:1--
\&
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.1\fR 
.if !d from \{\
.ds from \*[segment] 33r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 34r:2
.el .ds to \*[segment] 34r:2
(ff. 33r:1-34r:2)
.print-index-entry title Mh_35:id2293931 .. \n[PN]
.title
Prayer of the Cross (MDB 69 )
./title Mh_35:id2293931###--Mh_35 33r:1--
\&Incipit:
\(lqWors h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR i kors væræ m\fIeth\fR migh\(rq Explicit:
\(lqi naffn fadær och søn och th\fIe\fR n helligandh Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq Final rubric:
\(lqThe\fIn\fR næ for skreffnæ bøn diktæ och skreff een hiedærligh paffuæ i rom \&... so offtæ som han th\fIet\fR helligæ kors th\fIe\fR r vdi næffnær Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.2\fR 
.if !d from \{\
.ds from \*[segment] 34r:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 34r:16
.el .ds to \*[segment] 34r:16
(f. 34r:3-16)
.print-index-entry title Mh_35:id2294020 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 70 )
./title Mh_35:id2294020###--Mh_35 34r:3--
\&Incipit:
\(lq<I> æch betegnær migh m\fIeth\fR gudh hans værduga benedidhæ makt\(rq Explicit:
\(lqI naffn fadær och søn och th\fIe\fR n helligandh Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq MDB I,
No. 70
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.3\fR 
.if !d from \{\
.ds from \*[segment] 34r:17
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 34v:2
.el .ds to \*[segment] 34v:2
(f. 34r:17-34v:2)
.print-index-entry title Mh_35:id2294083 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 71 )
./title Mh_35:id2294083###--Mh_35 34r:17--
\& Rubric:
\(lqVor h\fIer\fR ræ sigær so i s\fIan\fR c\fIt\fR a birgitte bøgær \&... tha vil iæch for ladhæ hanom allæ allæ sinæ syndære Amen\(rq Incipit:
\(lqO h\fIer\fR ræ gudh iæch kiæ\fIn\fR nes migh suarligh ath haffuæ syndæt amodh thik\(rq Explicit:
\(lqthin bieskæ pinæ och hordhæ døth amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.4\fR 
.if !d from \{\
.ds from \*[segment] 34v:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 34v:10
.el .ds to \*[segment] 34v:10
(f. 34v:3-10)
.print-index-entry title Mh_35:id2294156 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 72 )
./title Mh_35:id2294156###--Mh_35 34v:3--
\& Rubric:
\(lqHuo som heelst the\fIn\fR næ æffth\fIe\fR r skreffnæ bøn læs gudæligh dagligh han skal m\fIeth\fR ganghæ i gledæn for vth\fIe\fR n allæ pinær Amen\(rq Incipit:
\(lqO h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e leffwindis gusz søn\(rq Explicit:
\(lqvdh aff thennæ grædhe fuldh dall Amen p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.5\fR 
.if !d from \{\
.ds from \*[segment] 34v:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 34v:22
.el .ds to \*[segment] 34v:22
(f. 34v:11-22)
.print-index-entry title Mh_35:id2294236 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ in his pain (MDB 73 )
./title Mh_35:id2294236###--Mh_35 34v:11--
\& Rubric:
\(lqHuo som the\fIn\fR næ æffth\fIe\fR r skreffnæ bøn læsær i vors h\fIer\fR ræ ih\fIes\fR us\fIchrist\fR i pinæs amy\fIn\fR nilsæ \&... vth\fIe\fR n gudh allæ iæ\fIn\fR ne Amen\(rq Incipit:
\(lqO korssæns høgilsæ o menløs blodh\(rq Explicit:
\(lqhielp myn siæl til ewi\fIn\fR nælighe salligh\fIet\fR Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.6\fR 
.if !d from \{\
.ds from \*[segment] 34v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 35v:5
.el .ds to \*[segment] 35v:5
(ff. 34v:23-35v:5)
.print-index-entry title Mh_35:id2294319 .. \n[PN]
.title
Prayer to the Trinity (MDB 74 )
./title Mh_35:id2294319###--Mh_35 34v:23--
\& Rubric:
\(lqhære byriæs een mærkæligh bøn aff then helligæ tre foldughet myggæt kostæligh ath læsæ huærdagh\(rq Incipit:
\(lqHeedær dygd makt och mektugh\fIet\fR væræ th\fIe\fR n helligæ trefoldugh\fIet\fR i iæn guddommæligh\fIet\fR\(rq Explicit:
\(lqEwi\fIn\fR næligh loff væræ th\fIe\fR n helligæ trefoldugh\fIet\fR och hiedær væræ een guddomæligh\fIet\fR ewi\fIn\fR næligh Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.7\fR 
.if !d from \{\
.ds from \*[segment] 35v:6
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 35v:16
.el .ds to \*[segment] 35v:16
(f. 35v:6-16)
.print-index-entry title Mh_35:id2294406 .. \n[PN]
.title
Prayer to the Trinity (MDB 75 )
./title Mh_35:id2294406###--Mh_35 35v:6--
\& Rubric:
\(lqItem huo som gudæligh huærdagh thissæ effth\fIe\fR r skreffnæ ordh læs i helligæ tre foldughetz ære \&... huilkæt damascen\fIus\fR skriffuær i sin bogh xv\(rq Incipit:
\(lqS\fIan\fR c\fIt\fR us S\fIan\fR c\fIt\fR us S\fIan\fR c\fIt\fR us d\fIomi\fR nus de\fIus\fR sabaoth\(rq Explicit:
\(lqS\fIan\fR c\fIt\fR us\fIet\fR inmortalis mis\fIer\fR ere nobis Amen\(rq
.print-index-entry language Mh_35:id2294489 .. \n[PN]
.language
Latin
./language Mh_35:id2294489 ... 
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.8\fR 
.if !d from \{\
.ds from \*[segment] 35v:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 35v:22
.el .ds to \*[segment] 35v:22
(f. 35v:16-22)
.print-index-entry title Mh_35:id2294512 .. \n[PN]
.title
Prayer to the Trinity (MDB 76 )
./title Mh_35:id2294512###--Mh_35 35v:16--
\& Rubric:
\(lqIæn a\fIn\fR nen loff sangh aff helligæ trefoldugh\fIet\fR\(rq Incipit:
\(lqHelligh helligh helligh æst thu h\fIer\fR ræ gudh vndær huis h\fIer\fR rædom ær allæ ænglæ skaræ\(rq Explicit:
\(lqo hellige trefoldugh\fIet\fR Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.9\fR 
.if !d from \{\
.ds from \*[segment] 35v:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 36v:21
.el .ds to \*[segment] 36v:21
(ff. 35v:22-36v:21)
.print-index-entry title Mh_35:id2294573 .. \n[PN]
.title
Prayer to the Trinity (MDB 77 )
./title Mh_35:id2294573###--Mh_35 35v:22--
\& Rubric:
\(lqItem sigæs the\fIn\fR næ effth\fIe\fR r skreffnæ loff sangh ath haffuæ sadan makt och dygdh \&... som damascen\fIus\fR skriffuær i libro xiv Amen\(rq Incipit:
\(lqO iæne alzom mektugæstæ gudh fadær oc søn och th\fIe\fR n helligand mektugh\fIet\fR visdom godhetz værnære\(rq Explicit:
\(lqO hellighæ trefoldugh\fIet\fR Amen p\fIate\fR r n\fIoste\fR r\(rq Final rubric:
\(lqThe\fIn\fR næ for skreffnæ tallæn troligh och gudæligh læst ær krafftugh modh allæ vodhæ paa iordæn och i haffuæth \&... Saa helligh ær the\fIn\fR næ for skreffnæ læsni\fIn\fR gh och loff sangh ath næppæligh til stedæs iæn værdzsæligh me\fIn\fR niskæ ath framføræ th\fIet\fR Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.10\fR 
.if !d from \{\
.ds from \*[segment] 36v:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 37r:6
.el .ds to \*[segment] 37r:6
(ff. 36v:22-37r:6)
.print-index-entry title Mh_35:id2294691 .. \n[PN]
.title
Praise of the Trinity,
Jesus Christ and the Virgin (MDB 78 )
./title Mh_35:id2294691###--Mh_35 36v:22--
\&Incipit:
\(lqO hellighæ och v atskiellæligh trefoldugh\fIet\fR ih\fIes\fR u\fIchrist\fR i korsfæst mandom\(rq Explicit:
\(lqO helligæ marie iomff\fIru\fR och modær væræ loff och æræ aff allæ creatur ewi\fIn\fR næligh e for vth\fIe\fR n ændæ Amen\(rq Final rubric:
\(lqThe\fIn\fR næ lidlæ bøn ær vd skreffuæt i ro\fIm\fR och til hi\fIn\fR næ ær giiffuæt tho thusind aar och ii hu\fIn\fR dræt och sextyue daghe Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.11\fR 
.if !d from \{\
.ds from \*[segment] 37r:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 37r:22
.el .ds to \*[segment] 37r:22
(f. 37r:7-22)
.print-index-entry title Mh_35:id2294781 .. \n[PN]
.title
Prayer to the Trinity (MDB 79 )
./title Mh_35:id2294781###--Mh_35 37r:7--
\&Incipit:
\(lqO<herræ> helligæ fadær och ewærdæligh gudh iæch bedær thik\(rq Explicit:
\(lqoch ælsk oss at iæch maa fi\fIn\fR næ thik i myn døsz timæ Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.12\fR 
.if !d from \{\
.ds from \*[segment] 37r:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 38v:11
.el .ds to \*[segment] 38v:11
(ff. 37r:23-38v:11)
.print-index-entry title Mh_35:id2294829 .. \n[PN]
.title
Prayers to Jesus Christ and the Virgin (MDB 80 )
./title Mh_35:id2294829###--Mh_35 37r:23--
\& Rubric:
\(lqeen læghæ brodær i s\fIanct\fR i bernardi ordæn togh sigh for een godh sedwonæ och læste huærdagh i xx aar føræ han dødhæ \&... han fongær vissæligh th\fIe\fR n sa\fIm\fR mæ nadhæ och affløsni\fIn\fR gh aff syndær Amen\(rq Incipit:
\(lqH\fIer\fR ræ ih\fIes\fR u\fIchrist\fR i leffwindis gusz søn och io\fIm\fR fru maria søn\(rq Explicit:
\(lqmedæn fræls migh raskæligh æffth\fIe\fR r thin signæth viliæ och storæ miskwndh Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.13\fR 
.if !d from \{\
.ds from \*[segment] 38v:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 39v:3
.el .ds to \*[segment] 39v:3
(ff. 38v:12-39v:3)
.print-index-entry title Mh_35:id2294922 .. \n[PN]
.title
Prayer in verse to the Five Wounds of Jesus Christ (MDB 81 )
./title Mh_35:id2294922###--Mh_35 38v:12--
\& Rubric:
\(lqTil huært værs och collecter som hær æffth\fIe\fR r skriffuæs \&... om thu læsær th\fIe\fR m m\fIeth\fR gudæligh\fIet\fR Amen\(rq Incipit:
\(lqHeel ih\fIes\fR u\fIchrist\fR e høgræ handh som korsfæst var a iødhæ landh\(rq Explicit:
\(lqoch i dødæn hielp migh th\fIet\fR diæfflen fongær ey makt hellær voldh ouær migh som thu m\fIeth\fR thit dyræ blodh løstæ Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.14\fR 
.if !d from \{\
.ds from \*[segment] 39v:4
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 40v:7
.el .ds to \*[segment] 40v:7
(ff. 39v:4-40v:7)
.print-index-entry title Mh_35:id2295001 .. \n[PN]
.title
Three prayers to Jesus Christ (MDB 82 )
./title Mh_35:id2295001###--Mh_35 39v:4--
\& Rubric:
\(lqThissæ tre stackæt effth\fIe\fR r skreffnæ bønær skal læsæs m\fIeth\fR tre p\fIate\fR r n\fIoste\fR r och aue maria \&... och han førær thieræ siæle til ewighæ glede Am\fIen\fR\(rq Incipit:
\(lqO Mildæ h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e my\fIn\fR gudh myn h\fIer\fR ræ myn skabær myn salligh giørær\(rq Explicit:
\(lqoch giiff allæ kristenæ siæle ewi\fIn\fR næligh gledæ Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.15\fR 
.if !d from \{\
.ds from \*[segment] 40v:8
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 41r:3
.el .ds to \*[segment] 41r:3
(ff. 40v:8-41r:3)
.print-index-entry title Mh_35:id2295089 .. \n[PN]
.title
Prayer to the Trinity (MDB 83 )
./title Mh_35:id2295089###--Mh_35 40v:8--
\& Rubric:
\(lqHuilkæn me\fIn\fR niskæ the\fIn\fR næ effth\fIe\fR r skreffne bøn læs m\fIeth\fR gudæligh\fIet\fR th\fIe\fR n helligæ trefoldugh\fIet\fR til loff och ære \&... hanom giøres amodh i iørdærigi Amen\(rq Incipit:
\(lqIæch op ladær myn hiærtens røst til ath loffuæ och ære thic th\fIe\fR n helligæ trefoldugh\fIet\fR\(rq Explicit:
\(lqfulkom the\fIn\fR næ stackæth<hiertens> loff i th\fIe\fR n helligæ trefoldughetz aasiøn i the\fIn\fR næ pu\fIn\fR kt nw och ewi\fIn\fR næligh Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.16\fR 
.if !d from \{\
.ds from \*[segment] 41r:4
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 41v:8
.el .ds to \*[segment] 41v:8
(f. 41r:4-41v:8)
.print-index-entry title Mh_35:id2295202 .. \n[PN]
.title
Prayer to Jesus Christ in his pain (MDB 84 )
./title Mh_35:id2295202###--Mh_35 41r:4--
\& Rubric:
\(lqS\fIan\fR c\fIt\fR us gregori\fIus\fR paffuæ gaff til the\fIn\fR næ effth\fIe\fR r skreffnæ bøn saa myghæt afflath som \&... ee huo th\fIe\fR m læs m\fIeth\fR gudæligh\fIe\fR t Amen\(rq Incipit:
\(lqO kiære h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e thu som æst alzom nadhæ fullæste\(rq Explicit:
\(lqoch giiff mik ryffwilsæ i mith hiærtæ for allæ mynæ syndær Amen p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.17\fR 
.if !d from \{\
.ds from \*[segment] 41v:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 47v:8
.el .ds to \*[segment] 47v:8
(ff. 41v:9-47v:8)
.print-index-entry title Mh_35:id2295299 .. \n[PN]
.title
Prayer to the limbs of Jesus Christ (MDB 85 )
./title Mh_35:id2295299###--Mh_35 41v:9--
\& Rubric:
\(lqeen helligh qwi\fIn\fR næ astwndæt ath vidhæ taal paa ih\fIes\fR u\fIchrist\fR i vndær och saar \&... som han frælstæ S\fIan\fR c\fIt\fR æ powæl fra haffzæns bu\fIn\fR dh Amen\(rq Incipit:
\(lqO sødhæ h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e ewerdæligh thieræ sødmæ swo som thik ælskær\(rq Explicit:
\(lqoch skiænk hi\fIn\fR næ aff th\fIe\fR n guddoms kalk huilkæn som thu haffuær th\fIe\fR m allæ iæt th\fIe\fR r thic m\fIeth\fR thissæ bønær thie\fIn\fR ner m\fIeth\fR so kiærlighetz how och so gudælighetz akt Amen p\fIate\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.18\fR 
.if !d from \{\
.ds from \*[segment] 47v:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 48v:1
.el .ds to \*[segment] 48v:1
(ff. 47v:9-48v:1)
.print-index-entry title Mh_35:id2295415 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 86 )
./title Mh_35:id2295415###--Mh_35 47v:9--
\& Rubric:
\(lqHuo som the\fIn\fR næ effth\fIe\fR r skreffne bøn læs huær dagh \&... tha om vænd\fIe\fR r gudh the pinæ til ewi\fIn\fR næligh gledhæ Amen\(rq Incipit:
\(lqO godhæ ih\fIes\fR u O alt mildistæ ih\fIes\fR u O alt sødistæ ih\fIes\fR u\(rq Explicit:
\(lqhwilkæn som ær vey oc sandh\fIet\fR och iæn signet fruct iomfru maria Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.19\fR 
.if !d from \{\
.ds from \*[segment] 48v:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 49r:18
.el .ds to \*[segment] 49r:18
(ff. 48v:2-49r:18)
.print-index-entry title Mh_35:id2295492 .. \n[PN]
.title
Three prayers to Our Lord Jesus Christ (MDB 87 )
./title Mh_35:id2295492###--Mh_35 48v:2--
\& Rubric:
\(lq<I> oha\fIn\fR nes paffuæ th\fIe\fR n annen til tyffwindhæ stadfæste thissæ tre æffth\fIe\fR r skreffnæ bønær til th\fIe\fR n fyrstæ gaff han ottæ hwndræt thusindh aar afflath for nadæligh syndær Amen\(rq Incipit:
\(lqH\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e iæch vslæ syndugæ me\fIn\fR niskæ\(rq Explicit:
\(lqath vi moghæ ewi\fIn\fR neligh m\fIeth\fR thik bliffuæ Amen migh hobæs\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.20\fR 
.if !d from \{\
.ds from \*[segment] 49r:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 51r:23
.el .ds to \*[segment] 51r:23
(ff. 49v:19-51r:23)
.print-index-entry title Mh_35:id2295584 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ for the owner of the book (MDB 88 )
./title Mh_35:id2295584###--Mh_35 49r:19--
\& Rubric:
\(lqHuo som the\fIn\fR næ effth\fIe\fR r skreffnæ bøn læser gudæligh huærdagh han fongær for ladilsæ aff allæ sinæ synd\fIe\fR r \&... tha skal han til forne læse thissæ tre psalmer som<ær>
.print-index-entry title Mh_35:id2295621 .. \n[PN]
.title
De\fIus\fR in no\fIm\fR i\fIn\fR e tuo
./title Mh_35:id2295621###--Mh_35 --
\&
.print-index-entry title Mh_35:id2295637 .. \n[PN]
.title
De\fIus\fR misereatur n\fIostr\fR i
./title Mh_35:id2295637###--Mh_35 --
\&
.print-index-entry title Mh_35:id2295649 .. \n[PN]
.title
De p\fIro\fR fundis
./title Mh_35:id2295649###--Mh_35 --
\& och skal the\fIn\fR næ bøn læsæs m\fIeth\fR stor attroels och stor gudæligh\fIet\fR och m\fIeth\fR ødhmygt hiærte Amen\(rq Incipit:
\(lqH\fIer\fR ræ gudh alz voldugæstæ fadær och søn och th\fIe\fR n helligandh giiff mik thin vuærdugæ thienistæ qwi\fIn\fR næ
.print-index-entry name Mh_35:id2295694 .. \n[PN]
.name
karine lodwigs dottær
./name Mh_35:id2295694
\& ouær ath vi\fIn\fR næ\(rq Explicit:
\(lqthu som leffwær styrær och regnerær m\fIeth\fR gudh fadær och th\fIe\fR n helligandh nw och ewi\fIn\fR neligh Amen p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.21\fR 
.if !d from \{\
.ds from \*[segment] 51v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 51v:16
.el .ds to \*[segment] 51v:16
(f. 51v:1-16)
.print-index-entry title Mh_35:id2295749 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 89 )
./title Mh_35:id2295749###--Mh_35 51v:1--
\& Rubric:
\(lqThe\fIn\fR æ effth\fIe\fR r skreffnæ bøn giordhæ s\fIan\fR c\fIt\fR us augustin\fIus\fR och huo hi\fIn\fR næ dagligh læs paa sin knæ han skal ey dø i dødæligh syndær vth\fIe\fR n han syndær th\fIe\fR r apa Amen\(rq Incipit:
\(lqO thu vbegribæligh mildh\fIet\fR skodhæ mig vslæ syndære\(rq Explicit:
\(lqskrabæ aff mynæ syndærs vtalligh\fIet\fR m\fIeth\fR thin misku\fIn\fR dh mangæ foldh\fIet\fR Amen p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.22\fR 
.if !d from \{\
.ds from \*[segment] 51v:17
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 52v:24
.el .ds to \*[segment] 52v:24
(ff. 51v:17-52v:24)
.print-index-entry title Mh_35:id2295854 .. \n[PN]
.title
Prayer to Jesus Christ in his pain (MDB 90 )
./title Mh_35:id2295854###--Mh_35 51v:17--
\& Rubric:
\(lq<I> æn godh bøn læssindæ nar gusz ligom lyfftes til huilkæn paffuæ benedict\fIus\fR th\fIe\fR n tolfftæ aff the\fIet\fR naffn gaff allæ ræth skrifftedæ me\fIn\fR niskæ \&... huilkæt for\fIskreff\fR ne afflath skal bliffuæ varingh til ewighæ tidh Amen\(rq Incipit:
\(lqO Miskwndæligh h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e Iæch bedær thik for th\fIe\fR n storæ kiærlighet thu ælskæt me\fIn\fR niskæn m\fIeth\fR\(rq Explicit:
\(lqthu som leffw\fIer\fR och styrær m\fIeth\fR fadæren och th\fIe\fR n hellighandh efor vth\fIe\fR n ænde Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.23\fR 
.if !d from \{\
.ds from \*[segment] 52v:25
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 54r:3
.el .ds to \*[segment] 54r:3
(ff. 52v:25-54r:3)
.print-index-entry title Mh_35:id2295972 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 91 )
./title Mh_35:id2295972###--Mh_35 52v:25--
\& Rubric:
\(lqHwo som the\fIn\fR ne effth\fIe\fR r skreffnæ bøn læsær i nogær mæsse \&... the vare fæm thusindh och firæ hwndræt och trystywæ och sex Amen\(rq Incipit:
\(lqHeedær och loff och offær giør iæch thic ewi\fIn\fR neligh fadær och eemektugæste gudh\(rq Explicit:
\(lqtil vor ydærste timæ th\fIe\fR r vi i værden leffuæ Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.24\fR 
.if !d from \{\
.ds from \*[segment] 54r:4
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 55v:1
.el .ds to \*[segment] 55v:1
(ff. 54r:4-55v:1)
.print-index-entry title Mh_35:id2296043 .. \n[PN]
.title
Prayer to the body of Christ,
used in the Holy Communion (MDB 92 )
./title Mh_35:id2296043###--Mh_35 54r:4--
\& Rubric:
\(lqHuo som the\fIn\fR næ effth\fIe\fR r skreffnæ bøn læs hanom ko\fIm\fR mær xx godhæ tingh th\fIe\fR r aff \&... th\fIet\fR giiffuæ os<gudh> alzom mektugæste Amen\(rq Incipit:
\(lqH\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e thu som æst th\fIe\fR n leffwindes gusz søn\(rq Explicit:
\(lqthu som myn sødiste och aldræ kiæristæ h\fIer\fR ræ och gudh ær ewi\fIn\fR næligh Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.25\fR 
.if !d from \{\
.ds from \*[segment] 55v:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 56r:14
.el .ds to \*[segment] 56r:14
(ff. 55v:2-56r:14)
.print-index-entry title Mh_35:id2296138 .. \n[PN]
.title
Prayer in verse to Our Lord Jesus Christ (MDB 93 )
./title Mh_35:id2296138###--Mh_35 55v:2--
\& Rubric:
\(lqHæræ byriæs een godh bøn aff vor kiære h\fIer\fR ræ ih\fIes\fR us\fIchrist\fR us och ær ganszæ godh ath læsæ huær syndagh han\fIom\fR til loff och ære\(rq Incipit:
\(lqSignæth see th\fIe\fR n dyræ dagh Signæth see th\fIe\fR n h\fIer\fR ræ os hanom gaff\(rq Explicit:
\(lqladh os ey vorde i ræszæl grebæn och ey i syndæn grebæn Am\fIen\fR\(rq Cfr.
the Swedish
.print-index-entry title Mh_35:id2296202 .. \n[PN]
.title
Dagvise
./title Mh_35:id2296202###--Mh_35 --
\&
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.26\fR 
.if !d from \{\
.ds from \*[segment] 56r:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 56v:20
.el .ds to \*[segment] 56v:20
(f. 56r:15-56v:20)
.print-index-entry title Mh_35:id2296222 .. \n[PN]
.title
Prayer to Our Lord Jesus Christ (MDB 94 )
./title Mh_35:id2296222###--Mh_35 56r:15--
\& Rubric:
\(lqHære byriæs iæn myggæth godh<bøn> aff vor h\fIer\fR ræ som man skal giærne læsæ huærdagh och tackæ gudh for allæ hans gode giærni\fIn\fR gær\(rq Incipit:
\(lqVælsignæth være gudh fadær och søn och th\fIe\fR n helligand\(rq Explicit:
\(lqSignæth være hans naffn och loffwæth ewi\fIn\fR næligh ee for vth\fIe\fR n ænde Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.27\fR 
.if !d from \{\
.ds from \*[segment] 56v:21
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 56v:24
.el .ds to \*[segment] 56v:24
(f. 56v:21-24)
.print-index-entry title Mh_35:id2296297 .. \n[PN]
.title
Prayers to Our Lord Jesus Christ (MDB 94.2 )
./title Mh_35:id2296297###--Mh_35 56v:21--
\& Rubric:
\(lqTill thissæ efftær skriffnæ bønær ær giffuæt xx thusindh aar afflath iiii xx aar och iiii daghæ och the skullæ læsæs for sadant figure som ih\fIes\fR us\fIchrist\fR us\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.28\fR 
.if !d from \{\
.ds from \*[segment] 57r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 59v:6
.el .ds to \*[segment] 59v:6
(ff. 57r:1-59v:6)
.print-index-entry title Mh_35:id2296343 .. \n[PN]
.title
Nine prayers to the body of Christ,
used in the Holy Communion (MDB 95 )
./title Mh_35:id2296343###--Mh_35 57r:1--
\&Begins defectively:
\(lqtær thin signedhæ viliæ Amen p\fIate\fR r n\fIoste\fR r Aue\(rq Explicit:
\(lqoch ladh migh ey skiliæs vidh thik efor vth\fIe\fR n ænde Amen p\fIate\fR r n\fIoste\fR r Aue ma\fIri\fR a\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.29\fR 
.if !d from \{\
.ds from \*[segment] 59v:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 60r:20
.el .ds to \*[segment] 60r:20
(ff. 59v:7-60r:20)
.print-index-entry title Mh_35:id2296407 .. \n[PN]
.title
Prayer to the body of Christ (MDB 96 )
./title Mh_35:id2296407###--Mh_35 59v:7--
\& Rubric:
\(lqS\fIan\fR c\fIt\fR us anastaci\fIus\fR paffwæ i rom giorde the\fIn\fR næ effth\fIe\fR r skreffnæ bøn \&... och huo th\fIe\fR n læs gudæligh han ey døør førræ han fongær gusz ligo\fIm\fR mæ i hans ydærstæ timæ Amen\(rq Incipit:
\(lqO aldræ værdugæstæ gudh och h\fIer\fR ræ och skabær\(rq Explicit:
\(lqoch loff m\fIeth\fR thik efor vth\fIe\fR n ænde Amen p\fIate\fR r n\fIoste\fR r Aue\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.30\fR 
.if !d from \{\
.ds from \*[segment] 60r:21
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 61r:21
.el .ds to \*[segment] 61r:21
(ff. 60r:21-61r:21)
.print-index-entry title Mh_35:id2296500 .. \n[PN]
.title
Prayer to the body of Christ,
used in the Holy Communion (MDB 97 )
./title Mh_35:id2296500###--Mh_35 60r:21--
\& Rubric:
\(lqHære byriæs iæn mygæth godh bøn som man skal giærne læsæ før man tagær gusz ligom\(rq Incipit:
\(lqO h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e m\fIeth\fR skielffwindæ samwidhæ gaar iæch fram ath vntfongæ thit vælsignedæ kiødh\(rq Explicit:
\(lqoch myn siæls krops stærkæ værn modh dieffwilsæns gienwordilsæ och fræstilsæ och mit leffnetz atroligh och hielso\fIm\fR mæligt ændeligt Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.31\fR 
.if !d from \{\
.ds from \*[segment] 61r:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 62r:15
.el .ds to \*[segment] 62r:15
(ff. 61r:22-62r:15)
.print-index-entry title Mh_35:id2296572 .. \n[PN]
.title
Prayer to the body of Christ,
used in the Holy Communion (MDB 98 )
./title Mh_35:id2296572###--Mh_35 61r:22--
\& Rubric:
\(lqHære byriæs een mygæth godh bøn som man skal læsæ føræ han tagær gusz benedidæ ligo\fIm\fR mæ\(rq Incipit:
\(lqO h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e huo hellær<huilken> ær iæch at iæch tørff gangæ til thit bordh\(rq Explicit:
\(lqath iæch maa thic gledæligh skodhæ i thin ewerdælighæ ære Amen p\fIate\fR r n\fIoste\fR r Aue maria aue\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.32\fR 
.if !d from \{\
.ds from \*[segment] 62r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 62r:24
.el .ds to \*[segment] 62r:24
(f. 62r:16-24)
.print-index-entry title Mh_35:id2296649 .. \n[PN]
.title
Prayer to God the Father,
used in the Holy Communion (MDB 99 )
./title Mh_35:id2296649###--Mh_35 62r:16--
\& Rubric:
\(lqHære byriæs een godh bøn som skal læsæs førre thu tag\fIer\fR gusz ligo\fIm\fR mæ\(rq Incipit:
\(lqO<h>\fIer\fR ræ gudh alz voldugær och ewærdeligh fadær vndh migh\(rq Explicit:
\(lqath fonghæ mynæ syndærs for ladilsæ och opp fyllæs m\fIeth\fR thin alzo helligæste andh Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.33\fR 
.if !d from \{\
.ds from \*[segment] 62v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 63r:5
.el .ds to \*[segment] 63r:5
(ff. 62v:1-63r:5)
.print-index-entry title Mh_35:id2296716 .. \n[PN]
.title
Prayer to the Virgin,
used in the Holy Communion (MDB 100 )
./title Mh_35:id2296716###--Mh_35 62v:1--
\& Rubric:
\(lqiæn godh bøn som skal læsæs førre thu tag\fIer\fR gusz benedidhe ligo\fIm\fR mæ\(rq Incipit:
\(lqAll ælskæligæste fruæ och alzo sædeligæste iomfru maria til thik ær mith høgæste hob næst gudh\(rq Explicit:
\(lqtil ewærdæligh gledhæ och ære m\fIeth\fR gudh ewi\fIn\fR næligh efor vth\fIe\fR n ændhæ Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.34\fR 
.if !d from \{\
.ds from \*[segment] 63r:6
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 63v:8
.el .ds to \*[segment] 63v:8
(f. 63r:6-63v:8)
.print-index-entry title Mh_35:id2296789 .. \n[PN]
.title
Prayer to the body of Christ,
used in the Holy Communion (MDB 101 )
./title Mh_35:id2296789###--Mh_35 63r:6--
\& Rubric:
\(lqHære byriæs een godh bøn aff vor h\fIer\fR ræ so\fIm\fR skal slæses siden thu haw\fIer\fR taget gusz ligo\fIm\fR me\(rq Incipit:
\(lqOors h\fIer\fR ræ ih\fIes\fR u dyræ ligo\fIm\fR mæ som iæch vuærdugæ me\fIn\fR niskæ diærffwæs til ath vntfonghæ\(rq Explicit:
\(lqtha vndh migh th\fIet\fR for thin vælsignedhæ mod\fIe\fR r iomfru maria och thinæ helligæns bønæ Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.35\fR 
.if !d from \{\
.ds from \*[segment] 63v:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 64r:2
.el .ds to \*[segment] 64r:2
(ff. 63v:9-64r:2)
.print-index-entry title Mh_35:id2296895 .. \n[PN]
.title
Prayer to the body of Christ,
used in the Holy Communion (MDB 102 )
./title Mh_35:id2296895###--Mh_35 63v:9--
\& Rubric:
\(lqHære byriæs een godh bøn so\fIm\fR skal læses sidæn thu haffw\fIer\fR tagæt gusz ligo\fIm\fR mæ\(rq Incipit:
\(lqO helligæ h\fIer\fR ræs ih\fIes\fR u\fIchrist\fR i siæl hellighe giør migh\(rq Explicit:
\(lqth\fIe\fR r til ath iæch skal loffwæ thik m\fIeth\fR thinæ helligæ ænglæ och gledæs m\fIeth\fR thic ewi\fIn\fR næligh Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.36\fR 
.if !d from \{\
.ds from \*[segment] 64r:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 64v:11
.el .ds to \*[segment] 64v:11
(f. 64r:3-64v:11)
.print-index-entry title Mh_35:id2296980 .. \n[PN]
.title
Three prayers to God the Father,
used in the Holy Communion (MDB 103 )
./title Mh_35:id2296980###--Mh_35 64r:3--
\& Rubric:
\(lqFyrst thu haffwær tagæth gusz benedidhæ och sødistæ ligo\fIm\fR mæ \&... skalt thu so sighæ som hære æffth\fIe\fR r skriffwæs\(rq Incipit:
\(lqGudh fadær for ladh migh th\fIe\fR t iæch icki saa gudh frittæligh haffwær tagæt\(rq Explicit:
\(lqoch rætte bønæ ath giøræ i thin helligæ thie\fIn\fR nistæ Amen p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.1.37\fR 
.if !d from \{\
.ds from \*[segment] 64v:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 64v:23
.el .ds to \*[segment] 64v:23
(f. 64v:12-23)
.print-index-entry title Mh_35:id2297050 .. \n[PN]
.title
Prayer to the body of Christ (MDB 104 )
./title Mh_35:id2297050###--Mh_35 64v:12--
\& Rubric:
\(lqHwo som the\fIn\fR næ lidlæ bøn læsær tri\fIn\fR næ si\fIn\fR næ m\fIeth\fR gudæligh\fIet\fR nar han haffuær vntfongæt \&... och in tændh kiærligh\fIet\fR til ih\fIes\fR u\fIchrist\fR i pinæ och dødh\(rq Incipit:
\(lqO Sødhæ h\fIer\fR ræ ih\fIes\fR u\fIchrist\fR e dyræ benedidhæ ligo\fIm\fR mæ giøm myn siæl til ewi\fIn\fR næligh liiff AMEN\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2\fR 
.if !d from \{\
.ds from \*[segment] 64v:24
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 89r:10
.el .ds to \*[segment] 89r:10
(ff. 64v:24-89r:10)
.print-index-entry title Mh_35:id2297144 .. \n[PN]
.title
Prayers to the Virgin
./title Mh_35:id2297144###--Mh_35 64v:24--
\&
.print-index-entry title Mh_35:id2297153 .. \n[PN]
.title
Vor Frue bønner
./title Mh_35:id2297153###--Mh_35 64v:24--
\& Rubric:
\(lqHære byriæs vor fruæ bønær\(rq
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.1\fR 
.if !d from \{\
.ds from \*[segment] 65r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 69v:2
.el .ds to \*[segment] 69v:2
(ff. 65r:1-69v:2)
.print-index-entry title Mh_35:id2297182 .. \n[PN]
.title
The Joys of the Virgin.
Ten prayers to the joy of the Virgin (MDB 105 )
./title Mh_35:id2297182###--Mh_35 65r:1--
\& Rubric:
\(lqWilt thu vidhæ huræ thissæ æfft\fIe\fR r skreffne bønær i th\fIet\fR te iørderigi ær kome\fIn\fR \&... troendis at the fonger vissæligh hielp aff iomfrw ma\fIri\fR a i alle thieres bøn\(rq Incipit:
\(lqMaria iech bedær thik och paa my\fIn\fR ner thic for the\fIn\fR store frygd och ouer flødughæ frygd\(rq Explicit:
\(lqladh thin barmhiærtugh\fIet\fR skie\fIn\fR næ paa mik och fuldkom myn bøn æfftær thin nadhæ och æfftær myn begieringh Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.2\fR 
.if !d from \{\
.ds from \*[segment] 69v:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 71v:13
.el .ds to \*[segment] 71v:13
(ff. 69v:3-71v:13)
.print-index-entry title Mh_35:id2297266 .. \n[PN]
.title
Prayer to the Virgin (MDB 106 )
./title Mh_35:id2297266###--Mh_35 69v:3--
\& Rubric:
\(lqHwilke\fIn\fR me\fIn\fR niskæ som thi\fIn\fR ne æfft\fIe\fR r skreffnæ bøn læsær j xxx daue for vor fruæ billet m\fIeth\fR hiærtens kiærligh\fIet\fR \&... hiluidi skrigær then ilzske mordær skieluer rædes och frycter och hylær\(rq Incipit:
\(lqÆrie hielset och louet være thu iomfru maria thu all ærlixtæ\(rq Explicit:
\(lqth\fIet\fR ær th\fIet\fR ewi\fIn\fR neligh liff i then ewi\fIn\fR neligh gledhæ Ame\fIn\fR p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.3\fR 
.if !d from \{\
.ds from \*[segment] 71v:14
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 72r:15
.el .ds to \*[segment] 72r:15
(ff. 71v:14-72r:15)
.print-index-entry title Mh_35:id2297364 .. \n[PN]
.title
Prayer to the Virgin (MDB 107 )
./title Mh_35:id2297364###--Mh_35 71v:14--
\& Rubric:
\(lqNær korss\fIet\fR ær opp tagh\fIet\fR paa poskæ morgæn \&... ath thu skalt ioo frælses vde\fIn\fR thyffuel Ame\fIn\fR\(rq Incipit:
\(lqO iomfru s\fIan\fR c\fIt\fR a maria iæch kwndgiør thiek ien stor gledhæ\(rq Explicit:
\(lqoc løsær mik aff alt vnt rykt och aff alle angestæ och aff alt nødh Ame\fIn\fR p\fIate\fR r n\fIoste\fR r aue\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.4\fR 
.if !d from \{\
.ds from \*[segment] 72r:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 75v:18
.el .ds to \*[segment] 75v:18
(ff. 72r:16-75v:18)
.print-index-entry title Mh_35:id2297444 .. \n[PN]
.title
The Sorrows of the Virgin
./title Mh_35:id2297444###--Mh_35 72r:16--
\&
.print-index-entry title Mh_35:id2297453 .. \n[PN]
.title
\fIJomfru Marias drøvelser (MDB 108 ).\fR
./title Mh_35:id2297453 ###--Mh_35 72r:16--
Rubric:
\(lqTh\fIet\fR læses at s\fIan\fR c\fIt\fR e ioha\fIn\fR nes ewangelsite han astu\fIn\fR dhe ath see iomfrw maria \&... och fongæ alle thissæ thing ther i thissæ bøner bedes som hære æffter skriffues Amen\(rq Incipit:
\(lqO maria sødistæ ih\fIes\fR u\fIchrist\fR i modær syndughæ me\fIn\fR niskes hielpære\(rq Explicit:
\(lqath iæch mattæ gledis m\fIeth\fR thin vælsign\fIet\fR søn ih\fIes\fR u\fIchrist\fR o och ha\fInu\fR m loffuæ ewi\fIn\fR neligh efor vden ændhæ Ame\fIn\fR p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.5\fR 
.if !d from \{\
.ds from \*[segment] 75v:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 76r:20
.el .ds to \*[segment] 76r:20
(ff. 75v:19-76r:20)
.print-index-entry title Mh_35:id2297571 .. \n[PN]
.title
Prayer to the Virgin
./title Mh_35:id2297571###--Mh_35 75v:19--
\&
.print-index-entry title Mh_35:id2297580 .. \n[PN]
.title
\fIJomfru Maria syv ord under korset (MDB 109 ).\fR
./title Mh_35:id2297580 ###--Mh_35 75v:19--
Rubric:
\(lqTh\fIet\fR tæ ær the syu ordh som iomfrw maria tallet vndær korss\fIet\fR \&... tha skal iomfru maria ko\fIm\fR mæ och frælæ hanwm aff alle hans nødh Ame\fIn\fR\(rq Incipit:
\(lqO ewærdeligh vth flydende kielde hwi æst thu\(rq Explicit:
\(lqi sa stoor nødh Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.6\fR 
.if !d from \{\
.ds from \*[segment] 76r:21
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 76v:6
.el .ds to \*[segment] 76v:6
(f. 76r:21-76v:6)
.print-index-entry title Mh_35:id2297650 .. \n[PN]
.title
Prayer to the sorrow of the Virgin
./title Mh_35:id2297650###--Mh_35 76r:21--
\&
.print-index-entry title Mh_35:id2297659 .. \n[PN]
.title
\fIKristi råb på korset (MDB 110 ).\fR
./title Mh_35:id2297659 ###--Mh_35 76r:21--
Rubric:
\(lqHæræ æffter skriffues ien mygh\fIet\fR godh bø\fIn\fR aff iomfrw maria drøwilsæ\(rq Incipit:
\(lqO Mildæ modær iomfrw maria\(rq Explicit:
\(lqfra alle andælig diæffuele vode och gri\fIm\fR me rob Am\fIen\fR p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.7\fR 
.if !d from \{\
.ds from \*[segment] 76v:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 81r:7
.el .ds to \*[segment] 81r:7
(ff. 76v:7-81r:7)
.print-index-entry title Mh_35:id2297728 .. \n[PN]
.title
Prayer to the joys and sorrows of the Virgin
./title Mh_35:id2297728###--Mh_35 76v:7--
\&
.print-index-entry title Mh_35:id2297738 .. \n[PN]
.title
\fIJomfru Marias glæder og drøvelser (MDB 111 ).\fR
./title Mh_35:id2297738 ###--Mh_35 76v:7--
Rubric:
\(lqHuo som thissæ gledær och thissæ drøffuelsær les \&... th\fIet\fR tæ gaff hun for s\fIan\fR c\fIt\fR i ancelm\fIus\fR bøn\(rq Incipit:
\(lqLoff hedær och æræ haffue thu iomfrw maria for thin æræ och værdugh\fIet\fR\(rq Explicit:
\(lqhwilke\fIn\fR som leffwær och regnerer ien b\fIe\fR n\fIe\fR didhæ gudh nw och ewi\fIn\fR neligh Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.8\fR 
.if !d from \{\
.ds from \*[segment] 81r:8
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 81r:23
.el .ds to \*[segment] 81r:23
(f. 81r:8-23)
.print-index-entry title Mh_35:id2297824 .. \n[PN]
.title
Prayer to the Virgin (MDB 112 )
./title Mh_35:id2297824###--Mh_35 81r:8--
\& Rubric:
\(lqHuo som thi\fIn\fR ne æffter skreffne bøn læsær m\fIeth\fR gudæligh\fIet\fR \&... sa mangæ daue skal han see io\fIm\fR f\fIru\fR maria førræ æn han døør Ame\fIn\fR\(rq Incipit:
\(lqHeel fruæ s\fIanc\fR c\fIt\fR a maria gusz modær\(rq Explicit:
\(lqoch bedh for myne sy\fIn\fR d\fIe\fR r Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.9\fR 
.if !d from \{\
.ds from \*[segment] 81r:24
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 81v:8
.el .ds to \*[segment] 81v:8
(f. 81r:24-81v:8)
.print-index-entry title Mh_35:id2297908 .. \n[PN]
.title
Prayer to the Virgin
./title Mh_35:id2297908###--Mh_35 81r:24--
\&
.print-index-entry title Mh_35:id2297917 .. \n[PN]
.title
\fIJomfru Marias kys (MDB 113 ).\fR
./title Mh_35:id2297917 ###--Mh_35 81r:24--
Rubric:
\(lqSaa thit och offtæ som thu les thi\fIn\fR næ bøn \&... som thu læstæ halff tridiæ si\fIn\fR ne xx aue maria\(rq Incipit:
\(lqO maria iæch bedær thik for the sødæ kys\(rq Explicit:
\(lqbarmhiærtugh\fIet\fR hoos gudh Amen Aue ma\fIri\fR a\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.10\fR 
.if !d from \{\
.ds from \*[segment] 81v:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 81v:21
.el .ds to \*[segment] 81v:21
(f. 81v:9-21)
.print-index-entry title Mh_35:id2297978 .. \n[PN]
.title
\fIPrayer to the Virgin (MDB 114 ).\fR
./title Mh_35:id2297978 ###--Mh_35 81v:9--
Rubric:
\(lqTh\fIet\fR seyæs ath ingen ær saa stor syndhær \&... i sin døsz thimæ hellær ændæligt\(rq Incipit:
\(lqO maria thu som æst alle dygde opp hou och fulkomelsæ\(rq Explicit:
\(lqoch ath gledis aff thin asiøn i hi\fIm\fR mærigis æræ Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.11\fR 
.if !d from \{\
.ds from \*[segment] 81v:22
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 82r:8
.el .ds to \*[segment] 82r:8
(ff. 81v:22-82r:8)
.print-index-entry title Mh_35:id2298033 .. \n[PN]
.title
Prayer to the Trinity and the Virgin (MDB 115 )
./title Mh_35:id2298033###--Mh_35 81v:22--
\& Rubric:
\(lqIen paue hede celestin\fIus\fR \&... læsær hi\fIn\fR næ m\fIeth\fR gudæligh\fIet\fR\(rq Incipit:
\(lqSign\fIet\fR væræ h\fIer\fR re s\fIan\fR c\fIt\fR e trinitatis\(rq Explicit:
\(lqmeræ æn thry thusindh foldh Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.12\fR 
.if !d from \{\
.ds from \*[segment] 82r:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 82r:23
.el .ds to \*[segment] 82r:23
(f. 82r:9-23)
.print-index-entry title Mh_35:id2298108 .. \n[PN]
.title
Prayer to the Virgin (MDB 116 )
./title Mh_35:id2298108###--Mh_35 82r:9--
\& Rubric:
\(lqTh\fIet\fR var ien fattugh møø \&... hu\fIn\fR ær mik saa taknæligher æn thusindh aue maria\(rq Incipit:
\(lqHeel maria fuldh m\fIeth\fR nadhæ\(rq Explicit:
\(lqoch alt hi\fIm\fR merigis hærskabs Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.13\fR 
.if !d from \{\
.ds from \*[segment] 82v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 82v:15
.el .ds to \*[segment] 82v:15
(f. 82v:1-15)
.print-index-entry title Mh_35:id2298174 .. \n[PN]
.title
Prayer to the Virgin (MDB 117 )
./title Mh_35:id2298174###--Mh_35 82v:1--
\& Rubric:
\(lqHuo som thi\fIn\fR ne æffter skreffne bøn læsær\(rq Incipit:
\(lqHeel maria the\fIn\fR helligæ trefoldughetz mynstær\(rq Explicit:
\(lqi alle my\fIn\fR nødh och myn sorigh Ame\fIn\fR p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.14\fR 
.if !d from \{\
.ds from \*[segment] 82v:16
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 82v:23
.el .ds to \*[segment] 82v:23
(f. 82v:16-23)
.print-index-entry title Mh_35:id2298239 .. \n[PN]
.title
Prayer to the Virgin (MDB 118 )
./title Mh_35:id2298239###--Mh_35 82v:16--
\& Rubric:
\(lqien stakket bøn aff iomfru maria \&... nar thu fra\fIm\fR gangær for io\fIm\fR fru maria billet\(rq Incipit:
\(lqO nadens fruæ omisku\fIn\fR deligh moder\(rq Explicit:
\(lqoch alle bedrøwæde hiærtæ Amen p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.15\fR 
.if !d from \{\
.ds from \*[segment] 83r:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 83v:12
.el .ds to \*[segment] 83v:12
(f. 83r:1-83v:12)
.print-index-entry title Mh_35:id2298302 .. \n[PN]
.title
Prayer to the joys of the Virgin (MDB 119 )
./title Mh_35:id2298302###--Mh_35 83r:1--
\& Rubric:
\(lqTil thissæ æffther skreffne bøner \&... M ars afflat och iii ars afflat\(rq Incipit:
\(lqGledes iomfru ih\fIes\fR u\fIcrist\fR i modær maria\(rq Explicit:
\(lqsom aldrigh for gaar och bliuer efor vden ændhæ Ame\fIn\fR p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.16\fR 
.if !d from \{\
.ds from \*[segment] 83v:13
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 84r:9
.el .ds to \*[segment] 84r:9
(ff. 83v:13-84r:9)
.print-index-entry title Mh_35:id2298371 .. \n[PN]
.title
Prayer to the Virgin (MDB 120 )
./title Mh_35:id2298371###--Mh_35 83v:13--
\& Rubric:
\(lqHæræ æfftær skriffues ien godh bø\fIn\fR som skal læses m\fIeth\fR fæm aue ma\fIri\fR a \&... och sey sa\(rq Incipit:
\(lqO Sødhæ iomfrw maria iæch bed\fIe\fR r thik for th\fIet\fR sorgæligh lydh\(rq Explicit:
\(lqath the moue vordæ thin søn vthen for tørnelsæ och myn siæl vden pinæ Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.17\fR 
.if !d from \{\
.ds from \*[segment] 84r:9
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 84r:18
.el .ds to \*[segment] 84r:18
(f. 84r:9-18)
.print-index-entry title Mh_35:id2298435 .. \n[PN]
.title
Prayer to the Virgin (MDB 121 )
./title Mh_35:id2298435###--Mh_35 84r:9--
\& Rubric:
\(lqIt\fIem\fR siden skulle man læsse tree aue maria och siden seyæ saa\(rq Incipit:
\(lqO alzo troligæstæ syndughæ me\fIn\fR niskens modær iomfrw maria\(rq Explicit:
\(lqoch thin modærligh hedær hære och ewi\fIn\fR nelig\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.18\fR 
.if !d from \{\
.ds from \*[segment] 84r:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 84v:11
.el .ds to \*[segment] 84v:11
(f. 84r:19-84v:11)
.print-index-entry title Mh_35:id2298491 .. \n[PN]
.title
Prayer to the Virgin (MDB 122 )
./title Mh_35:id2298491###--Mh_35 84r:19--
\& Rubric:
\(lqIen mygh\fIet\fR godh bøn aff iomfrw ma\fIri\fR a som i skal daueligh læsæ m\fIeth\fR gudæligh\fIet\fR\(rq Incipit:
\(lqO maria iomfrw ouer alle iomf\fIru\fR ær vær mik nær i th\fIe\fR n same thime\(rq Explicit:
\(lqth\fIet\fR vndhæ mik gudh fadær och søn och then helligh andh Ame\fIn\fR p\fIate\fR r n\fIoste\fR r Aue\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.19\fR 
.if !d from \{\
.ds from \*[segment] 84v:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 85r:9
.el .ds to \*[segment] 85r:9
(ff. 84v:12-85r:9)
.print-index-entry title Mh_35:id2298572 .. \n[PN]
.title
Prayer to the joys of the Virgin (MDB 123 )
./title Mh_35:id2298572###--Mh_35 84v:12--
\& Rubric:
\(lqPaa vor fruæ dagh i fastæ tha ladh bri\fIn\fR ne ix lyus \&... oc seyæ saa som hære æfftær skriffues\(rq Incipit:
\(lqO iomfru maria gusz modær for the\fIn\fR glede thu fæk\(rq Explicit:
\(lqI naffn gudh fad\fIe\fR r och søn och the\fIn\fR helligh andh Ame\fIn\fR p\fIate\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.20\fR 
.if !d from \{\
.ds from \*[segment] 85r:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 85v:1
.el .ds to \*[segment] 85v:1
(f. 85r:10-85v:1)
.print-index-entry title Mh_35:id2298640 .. \n[PN]
.title
Prayer to the Virgin (MDB 124 )
./title Mh_35:id2298640###--Mh_35 85r:10--
\& Rubric:
\(lqThi\fIn\fR næ æffter skreffne bøn hu\fIn\fR star i s\fIan\fR c\fIt\fR e birgite hi\fIn\fR nes bogh \&... frels\fIet\fR fraa hilwidis pine\(rq Incipit:
\(lqO S\fIan\fR c\fIt\fR a maria thu æst miskwnde\fIn\fR s modær\(rq Explicit:
\(lqfor ty thu nettær ingen misku\fIn\fR d som til thik bedis Amen p\fIate\fR r n\fIoste\fR r Aue\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.21\fR 
.if !d from \{\
.ds from \*[segment] 85v:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 85v:22
.el .ds to \*[segment] 85v:22
(f. 85v:2-22)
.print-index-entry title Mh_35:id2298730 .. \n[PN]
.title
A commitment to the Virgin (MDB 125 )
./title Mh_35:id2298730###--Mh_35 85v:2--
\& Rubric:
\(lqIen mygh\fIe\fR t godh bøn aff iomfrw maria som i skal læsæ fyrst om morge\fIn\fR\(rq Incipit:
\(lqHeel maria fuldh m\fIeth\fR nadhæ\(rq Explicit:
\(lqth\fIet\fR iæch aldrigh døør førræ æn iæch hauer for thient beggis edær vænskab och hyllæstæ Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.22\fR 
.if !d from \{\
.ds from \*[segment] 85v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 86r:14
.el .ds to \*[segment] 86r:14
(ff. 85v:23-86r:14)
.print-index-entry title Mh_35:id2298796 .. \n[PN]
.title
Prayer to the joy of the Virgin (MDB 126 )
./title Mh_35:id2298796###--Mh_35 85v:23--
\& Rubric:
\(lqHuo som thi\fIn\fR ne æffter skreffne bøn les huerdagh \&... och frælsæ th\fIe\fR m fraa dieffuelen och alt vnt\(rq Incipit:
\(lqGledh thik maria gusz fødær qwi\fIn\fR ne\(rq Explicit:
\(lqi vor døtzæns thime ewi\fIn\fR neligh hielp\fIer\fR och bed\fIe\fR rinne Ame\fIn\fR Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.23\fR 
.if !d from \{\
.ds from \*[segment] 86r:15
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 86r:19
.el .ds to \*[segment] 86r:19
(f. 86r:15-19)
.print-index-entry title Mh_35:id2298867 .. \n[PN]
.title
Prayer in verse to the Virgin (MDB 127 )
./title Mh_35:id2298867###--Mh_35 86r:15--
\& Rubric:
\(lqIen mygh\fIet\fR godh bøn aff iomfru maria\(rq Incipit:
\(lqHeel maria th\fIe\fR n skienende liliæ\(rq Explicit:
\(lqthu giø\fIm\fR me my\fIn\fR siæl fraa hiluidis qwide Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.24\fR 
.if !d from \{\
.ds from \*[segment] 86r:20
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 86v:11
.el .ds to \*[segment] 86v:11
(f. 86r:20-86v:11)
.print-index-entry title Mh_35:id2298927 .. \n[PN]
.title
Prayer in verse to the joys of the Virgin (MDB 128 )
./title Mh_35:id2298927###--Mh_35 86r:20--
\& Rubric:
\(lqHuo som thi\fIn\fR ne bøn les huærdagh\(rq Incipit:
\(lqGledes gusz modær iomfru maria fuldh m\fIeth\fR ære\(rq Explicit:
\(lqoch giffuæ mik the\fIn\fR ewi\fIn\fR neligh gledhæ Ame\fIn\fR p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.25\fR 
.if !d from \{\
.ds from \*[segment] 86v:12
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 87v:2
.el .ds to \*[segment] 87v:2
(ff. 86v:12-87v:2)
.print-index-entry title Mh_35:id2298996 .. \n[PN]
.title
Prayer in verse to the seven joys of the Virgin (MDB 129 )
./title Mh_35:id2298996###--Mh_35 86v:12--
\& Rubric:
\(lqHæræ æffter skriffues syw mygh\fIet\fR fore bøner aff iomfrw maria he\fIn\fR nes syw gledær och ær mygh\fIet\fR godhæ at læse\(rq Incipit:
\(lqGledis maria modær krist\(rq Explicit:
\(lqmi siæl mattæ fonghæ then frygd Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.26\fR 
.if !d from \{\
.ds from \*[segment] 87v:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 88v:17
.el .ds to \*[segment] 88v:17
(ff. 87v:3-88v:17)
.print-index-entry title Mh_35:id2299055 .. \n[PN]
.title
Prayer to the Virgin for all christian souls (MDB 130 )
./title Mh_35:id2299055###--Mh_35 87v:2--
\& Rubric:
\(lqHære æffter skriffues ien mygh\fIet\fR godh bøn aff iomfrw maria som skal læses for alle kristænæ siælæ\(rq Incipit:
\(lqO thu alzom feyærstæ och lystæligstæ yrtærgardh iomfrw maria\(rq Explicit:
\(lqæfftær thin b\fIe\fR n\fIe\fR didhæ søns viliæ nw och ewi\fIn\fR neligh efor vdæn ændhæ Amen p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.2.27\fR 
.if !d from \{\
.ds from \*[segment] 88v:18
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 89r:10
.el .ds to \*[segment] 89r:10
(ff. 88v:18-89r:10)
.print-index-entry title Mh_35:id2299125 .. \n[PN]
.title
A commitment to the Virgin (MDB 131 )
./title Mh_35:id2299125###--Mh_35 88v:18--
\& Rubric:
\(lqHæræ æfftær skriffwes ien mygh\fIet\fR god befalelse bøn aff iomfrw maria\(rq Incipit:
\(lqO maria alzo mektugæstæ och edelestæ iomfrw maria\(rq Explicit:
\(lqoch bliffuer e for vde\fIn\fR ændhæ Ame\fIn\fR p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3\fR 
.if !d from \{\
.ds from \*[segment] 89r:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 101r:24
.el .ds to \*[segment] 101r:24
(ff. 89r:11-101r:24)
.print-index-entry title Mh_35:id2299192 .. \n[PN]
.title
Prayers to St Anne
./title Mh_35:id2299192###--Mh_35 89r:11--
\&
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.1\fR 
.if !d from \{\
.ds from \*[segment] 89r:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 95:22
.el .ds to \*[segment] 95:22
(ff. 89r:11-95r:22)
.print-index-entry title Mh_35:id2299213 .. \n[PN]
.title
Ten prayers to st Anne (MDB 132 )
./title Mh_35:id2299213###--Mh_35 89r:11--
\& Rubric:
\(lqHæræ æfftær fylgær vnd\fIe\fR rligh nade och for gauæ som the fonghe som giærne hedræ s\fIan\fR c\fIt\fR a anna \&... han fongær hielp och salligh\fIet\fR til sin siæl och liiff Amen\(rq Incipit:
\(lqÆræ fuldh væræ thu hellighæ fruæ s\fIan\fR c\fIt\fR a anna aff ko\fIn\fR nigh dauidz slekt æst thu vdh voldh ouer alle qwi\fIn\fR ner\(rq Explicit:
\(lqat the for huærffuer mik syndzens for ladilsæ och th\fIet\fR ewi\fIn\fR neligh liiff æffter døden om vor h\fIer\fR ræ ih\fIes\fR um\fIchrist\fR um Amen\(rq Final rubric:
\(lqAlle the som giærne hedær iomf\fIru\fR maria ih\fIes\fR u\fIchrist\fR i modær th\fIe\fR m ær alle tidh stoor gusz nadhe \&... tha hører gwdh hans bøn och om vænder alle drøwelse til alzo største glede Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.2\fR 
.if !d from \{\
.ds from \*[segment] 95v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 97v:4
.el .ds to \*[segment] 97v:4
(ff. 95v:1-97v:4)
.print-index-entry title Mh_35:id2299341 .. \n[PN]
.title
Prayer to the fifteen joys of St Anne (MDB 133 )
./title Mh_35:id2299341###--Mh_35 95v:1--
\&Incipit:
\(lqO fruæ s\fIan\fR c\fIt\fR a anna gusz modær modær\(rq Explicit:
\(lqvedh thic ih\fIes\fR u\fIchrist\fR e som leuer och styrer och regnerer efor vden ændhe Am\fIen\fR\(rq Final rubric:
\(lqHuo som huerdagh thissæ xu gledær i s\fIan\fR c\fIt\fR a anna heller hi\fIn\fR ne dottær hedær gudeligh læsær huerdagh \&... och skal see iomfru maria och s\fIan\fR c\fIt\fR a anna i sin yderste thime\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.3\fR 
.if !d from \{\
.ds from \*[segment] 97v:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 97v:18
.el .ds to \*[segment] 97v:18
(f. 97v:5-18)
.print-index-entry title Mh_35:id2299428 .. \n[PN]
.title
Prayer to St Anne and the Virgin (MDB 134 )
./title Mh_35:id2299428###--Mh_35 97v:5--
\&Incipit:
\(lqHeel maria fuldh m\fIeth\fR nadhæ h\fIer\fR ren ær m\fIeth\fR thic thin nadæ væræ m\fIeth\fR mik\(rq Explicit:
\(lqaff thic ær fødh ih\fIes\fR us\fIchrist\fR us the\fIn\fR leffwindis gusz søn Ame\fIn\fR\(rq Final rubric:
\(lqAllexander paue gaff alle so\fIm\fR thi\fIn\fR ne lidele for skreffne bøn læser tre si\fIn\fR nær m\fIeth\fR tre p\fIate\fR r n\fIoste\fR r och aue maria for s\fIan\fR c\fIt\fR a anna billet x M aar for dødeligh syndær och xx M for nadælig syndær Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.4\fR 
.if !d from \{\
.ds from \*[segment] 97v:19
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 98r:3
.el .ds to \*[segment] 98r:3
(ff. 97v:19-98r:3)
.print-index-entry title Mh_35:id2299538 .. \n[PN]
.title
\fIPrayer to St Anne,
the mother of the Virgin (MDB 135 ).\fR
./title Mh_35:id2299538 ###--Mh_35 97v:19--
Incipit:
\(lqÆræ och hedær væræ thik værdugestæ modær s\fIan\fR c\fIt\fR a anna\(rq Explicit:
\(lqouer alle creature bodæ i hi\fIm\fR merigi och i iørdærigi ære Ame\fIn\fR p\fIate\fR r n\fIoste\fR r Aue maria\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.5\fR 
.if !d from \{\
.ds from \*[segment] 98r:4
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 98r:10
.el .ds to \*[segment] 98r:10
(f. 98r:4-10)
.print-index-entry title Mh_35:id2299600 .. \n[PN]
.title
Prayer to St Anne (MDB 136 )
./title Mh_35:id2299600###--Mh_35 98r:4--
\& Rubric:
\(lqFaal paa thine knæ och les ien aue maria aff s\fIan\fR c\fIt\fR a anna och sey sa som hæræ æffter staar\(rq Incipit:
\(lqHeel s\fIan\fR c\fIt\fR a anna iomfru maria ære m\fIeth\fR thik thu æst vælsignet ouer alle qwi\fIn\fR ner\(rq Explicit:
\(lqvælsignet ær thin liiffs fruct iomfru maria gusz modær p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.6\fR 
.if !d from \{\
.ds from \*[segment] 98r:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 98r:24
.el .ds to \*[segment] 98r:24
(f. 98r:11-24)
.print-index-entry title Mh_35:id2299677 .. \n[PN]
.title
\fIPrayer to St Anne,
mother of the Virgin (MDB 137 ).\fR
./title Mh_35:id2299677 ###--Mh_35 98r:11--
Incipit:
\(lqVælsign\fIet\fR være thu frue s\fIan\fR c\fIt\fR a anna for thy ath thu æst iomfru maria modær\(rq Explicit:
\(lqbedh for mik til thi\fIn\fR kiære dotter søn at han vælsigner mik ewi\fIn\fR neligh Ame\fIn\fR p\fIate\fR r n\fIoste\fR r Aue\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.7\fR 
.if !d from \{\
.ds from \*[segment] 98v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 98v:12
.el .ds to \*[segment] 98v:12
(f. 98v:1-12)
.print-index-entry title Mh_35:id2299747 .. \n[PN]
.title
Prayer to St Anne and her three daughters (MDB 138 )
./title Mh_35:id2299747###--Mh_35 98v:1--
\& Rubric:
\(lqLes tre aue maria s\fIan\fR c\fIt\fR a a\fIn\fR na til loff och hi\fIn\fR ne tre døttær\(rq Incipit:
\(lqO aldræ værdugæstæ modær s\fIan\fR c\fIt\fR a anna iæch bedær thic ødmygæligh\(rq Explicit:
\(lqoch for huerff bodhæ mik och th\fIe\fR m ath gledis m\fIeth\fR thik ewærdeligh Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.8\fR 
.if !d from \{\
.ds from \*[segment] 98v:13
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 99r:2
.el .ds to \*[segment] 99r:2
(ff. 98v:13-99r:2)
.print-index-entry title Mh_35:id2299825 .. \n[PN]
.title
Prayer to St Anne,
the Virgin and Jesus Christ (MDB 139 )
./title Mh_35:id2299825###--Mh_35 98v:13--
\& Rubric:
\(lqLes tre aue maria iomfru ma\fIri\fR a hiærte til loff och hi\fIn\fR ne kiære søn i\fIesus christus\fR och frue s\fIan\fR c\fIt\fR a anna\(rq Incipit:
\(lqO aldræ fructsomeligestæ modær fruæ s\fIan\fR c\fIt\fR a anna iæch bed\fIer\fR thik for then samen bindelsæ\(rq Explicit:
\(lqoch iæch mattæ bliue m\fIeth\fR hanw\fIm\fR ewi\fIn\fR neligh Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.9\fR 
.if !d from \{\
.ds from \*[segment] 99r:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 100r:24
.el .ds to \*[segment] 100r:24
(ff. 99r:3-100r:24)
.print-index-entry title Mh_35:id2299915 .. \n[PN]
.title
Prayer to St Anne (MDB 140 )
./title Mh_35:id2299915###--Mh_35 99r:3--
\& Rubric:
\(lqen iomfru var mygh\fIet\fR syrgendhe th\fIe\fR r om ath hun kwnde ey saa tiene io\fImfru\fR maria \&... och alt hi\fIm\fR merigis herskab astu\fIn\fR der thi\fIn\fR ko\fIm\fR me\(rq Incipit:
\(lqO ære fuldh frue s\fIan\fR c\fIt\fR a anna alt høueskeste qwi\fIn\fR ne\(rq Explicit:
\(lqth\fIet\fR vndhe os alle same\fIn\fR gudh fadær och søn oc then helligh andh iomfru maria och frue s\fIan\fR c\fIt\fR a anna Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.3.10\fR 
.if !d from \{\
.ds from \*[segment] 100v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 101r:24
.el .ds to \*[segment] 101r:24
(ff. 100v:1-101r:24)
.print-index-entry title Mh_35:id2300014 .. \n[PN]
.title
Prayer to St Anne (MDB 141 )
./title Mh_35:id2300014###--Mh_35 100v:1--
\& Rubric:
\(lqSyndugh\fIet\fR siæle hielsomeligh\fIet\fR skie\fIn\fR dæligh\fIet\fR Ære \&... faldh pa knæ och les thi\fIn\fR ne æfftær skreffne bøn\(rq Incipit:
\(lqHeel være thu helligæ frue s\fIan\fR c\fIt\fR a anna m\fIeth\fR ioachim thin kiære hosbunde\(rq Explicit:
\(lqvite sortem pacem presta celebrantibus tua festa Am\fIen\fR\(rq
.print-index-entry language Mh_35:id2300076 .. \n[PN]
.language
Danish and Latin
./language Mh_35:id2300076 ... 
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4\fR 
.if !d from \{\
.ds from \*[segment] 101v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 110v:10
.el .ds to \*[segment] 110v:10
(ff. 101v:1-110v:10)
.print-index-entry title Mh_35:id2300102 .. \n[PN]
.title
Prayers to various Angels and Saints
./title Mh_35:id2300102###--Mh_35 101v:1--
\&
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.1\fR 
.if !d from \{\
.ds from \*[segment] 101v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 102r:10
.el .ds to \*[segment] 102r:10
(ff. 101v:1-102r:10)
.print-index-entry title Mh_35:id2300124 .. \n[PN]
.title
Prayer to the daughters of St Anne (MDB 142 )
./title Mh_35:id2300124###--Mh_35 101v:1--
\& Rubric:
\(lqIen mygh\fIet\fR godh bøn aff the værduge hellighe tre maria oc ær the mygh\fIet\fR gode ath pa kalle i sin nødh\(rq Incipit:
\(lqO i edele systær bodæ maria iacobi och maria salome\(rq Explicit:
\(lqoch beholpe\fIn\fR aff theres bøner skulle nw leffue i hi\fIm\fR mærigi ewi\fIn\fR neligh<Ame>\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.2\fR 
.if !d from \{\
.ds from \*[segment] 102r:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 102v:3
.el .ds to \*[segment] 102v:3
(f. 102r:10-102v:3)
.print-index-entry title Mh_35:id2300194 .. \n[PN]
.title
Prayer to St Mary Magdalene (MDB 143 )
./title Mh_35:id2300194###--Mh_35 102r:10--
\& Rubric:
\(lqIen mygh\fIet\fR godh bøn aff frue s\fIan\fR c\fIt\fR a maria magdalena\(rq Incipit:
\(lqS\fIan\fR c\fIt\fR a maria magdalena gusz alzo\fIm\fR kiæristæ\(rq Explicit:
\(lqfor hi\fIn\fR ne bøn skyldh skulle vi settis i helligæ mensz skare Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.3\fR 
.if !d from \{\
.ds from \*[segment] 102v:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 103r:5
.el .ds to \*[segment] 103r:5
(ff. 102v:3-103r:5)
.print-index-entry title Mh_35:id2300264 .. \n[PN]
.title
Prayer to one's guardian angel (MDB 144 )
./title Mh_35:id2300264###--Mh_35 102v:3--
\& Rubric:
\(lqIen mygh\fIet\fR godh bøn aff gusz hellighe ængel\(rq Incipit:
\(lqO hellighæ gusz ængæl hwilke\fIn\fR som mik ær giuen til ien godh beuarelsæ\(rq Explicit:
\(lqoch antworde hi\fIn\fR ne for gut fadær och søn oc then helligh andh Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.4\fR 
.if !d from \{\
.ds from \*[segment] 103r:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 103v:3
.el .ds to \*[segment] 103v:3
(f. 103r:5-103v:3)
.print-index-entry title Mh_35:id2300319 .. \n[PN]
.title
Prayer to St John the Baptist (MDB 145 )
./title Mh_35:id2300319###--Mh_35 103r:5--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff s\fIan\fR c\fIt\fR e ioha\fIn\fR nes ewa\fIn\fR geliste ær han ien mygh\fIet\fR god nød hielp\fIer\fR\(rq Incipit:
\(lqO thu edele och helligæste s\fIan\fR c\fIt\fR e ioha\fIn\fR nes ewangeliste gusz væn\(rq Explicit:
\(lqoch leedh myn siæl til hi\fIm\fR merigis paredis æffter døden Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.5\fR 
.if !d from \{\
.ds from \*[segment] 103v:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 104r:1
.el .ds to \*[segment] 104r:1
(ff. 103v:3-104r:1)
.print-index-entry title Mh_35:id2300408 .. \n[PN]
.title
Prayer to St Andrew (MDB 146 )
./title Mh_35:id2300408###--Mh_35 103v:3--
\& Rubric:
\(lqIen mygh\fIet\fR god bøn aff s\fIan\fR c\fIt\fR e andreas appostele\(rq Incipit:
\(lqO s\fIan\fR c\fIt\fR e andreas alzo\fIm\fR stærkeste ih\fIes\fR u\fIchrist\fR i predicken\(rq Explicit:
\(lqien sandh gudh efor vden ænde Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.6\fR 
.if !d from \{\
.ds from \*[segment] 104r:2
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 104r:23
.el .ds to \*[segment] 104r:23
(f. 104r:2-23)
.print-index-entry title Mh_35:id2300486 .. \n[PN]
.title
Prayer to the Magi (MDB 147 )
./title Mh_35:id2300486###--Mh_35 104r:2--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff the værduge hellige tre kongær ær the mygh\fIet\fR gode\(rq Incipit:
\(lqKonge iæsp\fIer\fR konge melchior ko\fIn\fR gæ baltazar iæch bedær edær for alle eders naffn\(rq Explicit:
\(lqoch fra alle fare ther mik kan hendhe anten til siel hell\fIer\fR liiff Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.7\fR 
.if !d from \{\
.ds from \*[segment] 104r:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 104v:11
.el .ds to \*[segment] 104v:11
(f. 104r:23-104v:11)
.print-index-entry title Mh_35:id2300552 .. \n[PN]
.title
Prayer to St George (MDB 148 )
./title Mh_35:id2300552###--Mh_35 104r:23--
\& Rubric:
\(lqien mygh\fIet\fR god bøn aff riddær s\fIan\fR c\fIt\fR e iørgen ær han ien mygh\fIet\fR god nødhielp\fIer\fR\(rq Incipit:
\(lqO helligæ h\fIer\fR ræ s\fIan\fR c\fIt\fR e iørgen ien edele nødhielp\fIer\fR\(rq Explicit:
\(lqth\fIe\fR m hielp\fIer\fR thu til vors h\fIer\fR re rigi efor vden ændhæ Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.8\fR 
.if !d from \{\
.ds from \*[segment] 104v:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 104v:22
.el .ds to \*[segment] 104v:22
(f. 104v:11-22)
.print-index-entry title Mh_35:id2300642 .. \n[PN]
.title
Prayer to St Christopher (MDB 149 )
./title Mh_35:id2300642###--Mh_35 104v:11--
\& Rubric:
\(lqien mygh\fIet\fR god bøn aff h\fIer\fR re s\fIan\fR c\fIt\fR e cristofer\(rq Incipit:
\(lqO hellighæ h\fIer\fR ræ s\fIan\fR c\fIt\fR e cristofer gusz hellige martir\(rq Explicit:
\(lqoch m\fIeth\fR salligh<et> døø och fonge then ewi\fIn\fR neligh ære Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.9\fR 
.if !d from \{\
.ds from \*[segment] 104v:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 105r:9
.el .ds to \*[segment] 105r:9
(ff. 104v:23-105r:9)
.print-index-entry title Mh_35:id2300728 .. \n[PN]
.title
Prayer to St Lawrence (MDB 150 )
./title Mh_35:id2300728###--Mh_35 104v:23--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff s\fIan\fR c\fIt\fR e laurenti\(rq Incipit:
\(lqAldræ helligestæ laurentii messæ degen och gusz kiære martir\(rq Explicit:
\(lqoc at iæch mattæ faa ewi\fIn\fR neligh roo Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.10\fR 
.if !d from \{\
.ds from \*[segment] 105r:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 105v:3
.el .ds to \*[segment] 105v:3
(f. 105r:10-105v:3)
.print-index-entry title Mh_35:id2300789 .. \n[PN]
.title
Prayer to St Sebastian (MDB 151 )
./title Mh_35:id2300789###--Mh_35 105r:10--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff s\fIan\fR c\fIt\fR e sebastiane\(rq Incipit:
\(lqO S\fIan\fR c\fIt\fR e sebastiane bedh for mik vdi thi\fIn\fR ne nødh\(rq Explicit:
\(lqoch ko\fIm\fR me til th\fIet\fR ewi\fIn\fR neligh liiff æffter døden i naffn gudh fadær och søn och the\fIn\fR helligh andh Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.11\fR 
.if !d from \{\
.ds from \*[segment] 105v:3
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 105v:18
.el .ds to \*[segment] 105v:18
(f. 105v:3-18)
.print-index-entry title Mh_35:id2300873 .. \n[PN]
.title
Prayer to the Fourteen Holy Helpers
./title Mh_35:id2300873###--Mh_35 105v:3--
\&
.print-index-entry title Mh_35:id2300883 .. \n[PN]
.title
Bøn til de femten nødhjælpere (MDB 152 )
./title Mh_35:id2300883###--Mh_35 105v:3--
\& Rubric:
\(lqIen mygh\fIet\fR god bø\fIn\fR aff the xv nødhielper\(rq Incipit:
\(lqO i værdughæ xu nødhielp\fIer\fR Georgi\fIus\fR blasius\(rq Explicit:
\(lqoch bed\fIe\fR r for mik til vor h\fIer\fR ræ ih\fIesu\fR m\fIchristu\fR m Ame\fIn\fR\(rq The 15th helper is St Magnus from Allgäu
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.12\fR 
.if !d from \{\
.ds from \*[segment] 105v:18
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 106r:9
.el .ds to \*[segment] 106r:9
(ff. 105v:18-106r:9)
.print-index-entry title Mh_35:id2300966 .. \n[PN]
.title
Prayer to the Ten Thousand Martyrs
./title Mh_35:id2300966###--Mh_35 105v:18--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff the x thwsind ridd\fIe\fR r (MDB 153 )\(rq Incipit:
\(lqO thu alzom byrdugæstæ fadær hermolae o thu altzom helligæste martir\(rq Explicit:
\(lqoch alle gusz helligen skal bliue m\fIeth\fR ewi\fIn\fR neligh Ame\fIn\fR p\fIate\fR r n\fIoste\fR r\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.13\fR 
.if !d from \{\
.ds from \*[segment] 106r:10
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 107v:5
.el .ds to \*[segment] 107v:5
(ff. 106r:10-107v:5)
.print-index-entry title Mh_35:id2301046 .. \n[PN]
.title
Prayer in verse to St Erasmus (MDB 154 )
./title Mh_35:id2301046###--Mh_35 106r:10--
\& Rubric:
\(lqHuo som thi\fIn\fR ne æffter skreffne bø\fIn\fR les huer syndagh i iet aar \&... th\fIet\fR femtte at vors h\fIer\fR re hellige ængel komer til ha\fInu\fR m tre daue føre æn han dør oc fører ha\fIn\fR s siel til ewi\fIn\fR neligh glede Am\fIen\fR\(rq Incipit:
\(lqO S\fIan\fR c\fIt\fR e erasme hedærligh h\fIer\fR ræ och m\fIarti\fR r och gusz dyre biscop thu toldæ om syndagh pine och døt hielp nw bode til liff och siæl aff nødh\(rq Explicit:
\(lqladh os hære saa i iørdærigi thienæ ath vi moue fonghæ hi\fIm\fR mærigis gledhæ\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.14\fR 
.if !d from \{\
.ds from \*[segment] 107v:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 108r:3
.el .ds to \*[segment] 108r:3
(ff. 107v:5-108r:3)
.print-index-entry title Mh_35:id2301150 .. \n[PN]
.title
Prayer in verse to St Erasmus (MDB 155 )
./title Mh_35:id2301150###--Mh_35 107v:5--
\& Rubric:
\(lqIt\fIem\fR les tre oc halffierde si\fIn\fR ne xx aue ma\fIri\fR a huer sy\fIn\fR dag\(rq Incipit:
\(lqO S\fIan\fR c\fIt\fR e erasme bedh goth for mik och for os alle th\fIet\fR bede vi thik\(rq Explicit:
\(lqløs os aff syndhæ och aff sorigh alle same\fIn\fR th\fIet\fR bedhæ vi gudh och seyæ vi Amen\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.15\fR 
.if !d from \{\
.ds from \*[segment] 108r:4
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 108v:7
.el .ds to \*[segment] 108v:7
(f. 108r:4-108v:7)
.print-index-entry title Mh_35:id2301228 .. \n[PN]
.title
Prayer to St Francis (MDB 156 )
./title Mh_35:id2301228###--Mh_35 108r:4--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff h\fIer\fR re s\fIan\fR c\fItu\fR s francisc\fIus\fR ær han mygh\fIet\fR god at pa kalle i sin nødh \&... inge\fIn\fR kan fuld skriue han<s> dygd hell\fIer\fR godh\fIet\fR\(rq Incipit:
\(lqGledis ærligh fadær s\fIan\fR c\fIt\fR o francisco skie\fIn\fR nende m\fIeth\fR\fIchrist\fR i tege\fIn\fR\(rq Explicit:
\(lqthu ærlighe riddær som bar konigens vaben och bedh os syndens forladilsæ Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.16\fR 
.if !d from \{\
.ds from \*[segment] 108v:7
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 109r:5
.el .ds to \*[segment] 109r:5
(ff. 108v:7-109r:5)
.print-index-entry title Mh_35:id2301338 .. \n[PN]
.title
Prayer to St Antony (MDB 157 )
./title Mh_35:id2301338###--Mh_35 108v:7--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff h\fIer\fR re s\fIan\fR c\fIt\fR us antoni\fIus\fR ær han mygh\fIet\fR godh at hedre och pa kalle i sin nød\(rq Incipit:
\(lqO hellighe h\fIer\fR re s\fIan\fR c\fItu\fR s antoni\fIus\fR gusz vt voldh væn\(rq Explicit:
\(lqfrels mik aff vlideligh legoms plaue och pine bodhe til siæl och liiff Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.17\fR 
.if !d from \{\
.ds from \*[segment] 109r:5
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 109r:24
.el .ds to \*[segment] 109r:24
(f. 109r:5-24)
.print-index-entry title Mh_35:id2301424 .. \n[PN]
.title
Prayer to St Nicholas (MDB 158 )
./title Mh_35:id2301424###--Mh_35 109r:5--
\& Rubric:
\(lqien mygh\fIet\fR god bøn aff h\fIer\fR s\fIan\fR c\fIt\fR us nicholaus\(rq Incipit:
\(lqO S\fIan\fR c\fIt\fR e nicholae ære fuldh\fIcon\fR fessor oc alt helligæstæ biscop thu som æst the\fIn\fR hellighæ kirkens feyringh\(rq Explicit:
\(lqoc leed hi\fIn\fR ne til abrahams skiød oc th\fIe\fR r at gledis m\fIeth\fR gudh for vden ænde Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.18\fR 
.if !d from \{\
.ds from \*[segment] 109v:1
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 109v:24
.el .ds to \*[segment] 109v:24
(f. 109v:1-24)
.print-index-entry title Mh_35:id2301515 .. \n[PN]
.title
Prayer to St Catherine (MDB 159 )
./title Mh_35:id2301515###--Mh_35 109v:1--
\& Rubric:
\(lqIen mygh\fIet\fR god bøn aff iomfru s\fIan\fR c\fIt\fR a katerina\(rq Incipit:
\(lqGledis iomfru och martir s\fIan\fR c\fIt\fR a katerina och hielsæt være thu ære fuldh och vælskaptæ iomfru\(rq Explicit:
\(lqoch giø\fIm\fR mer os fra brad døth och hiluidis nød och iørdærigis skam nw och ewi\fIn\fR nelig Ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.19\fR 
.if !d from \{\
.ds from \*[segment] 109v:24
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 110r:22
.el .ds to \*[segment] 110r:22
(ff. 109v:24-110r:22)
.print-index-entry title Mh_35:id2301589 .. \n[PN]
.title
Prayer to St Gertrud (MDB 160 )
./title Mh_35:id2301589###--Mh_35 109v:24--
\& Rubric:
\(lqien mygh\fIet\fR godh bøn aff iomfru s\fIan\fR c\fIt\fR a ge<r> trudh\(rq Incipit:
\(lqHeel iomfru s\fIanct\fR a gertrudh tackæligh iomfru fødh aff ko\fIn\fR nighe slekt\(rq Explicit:
\(lqoch thin maiestat ær tackæligt m\fIeth\fR vor h\fIer\fR ræ ih\fIesu\fR m\fIchristu\fR m\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.20\fR 
.if !d from \{\
.ds from \*[segment] 110r:23
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 110v:10
.el .ds to \*[segment] 110v:10
(f. 110r:23-110v:10)
.print-index-entry title Mh_35:id2301674 .. \n[PN]
.title
Prayer to St Barbara (MDB 161 )
./title Mh_35:id2301674###--Mh_35 110r:23--
\& Rubric:
\(lqien mygh\fIet\fR god bø\fIn\fR aff s\fIan\fR c\fIt\fR a barbara\(rq Incipit:
\(lqO thu værdugæ iomfru s\fIan\fR c\fIt\fR a barabra iæch v værdughæ me\fIn\fR niskæ iæch beder thik fir thin harde pine\(rq Explicit:
\(lqth\fIet\fR sign\fIet\fR gusz legome at fonge i myn siste time och ew\fIer\fR delig liiff æffter døde\fIn\fR Am\fIen\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.21\fR 
.if !d from \{\
.ds from \*[segment] 110v:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 112v:3
.el .ds to \*[segment] 112v:3
(ff. 110v:11-112v:3)
.print-index-entry title Mh_35:id2301763 .. \n[PN]
.title
Prayers copied from Christiern Pedersen's Book of Hours
./title Mh_35:id2301763###--Mh_35 110v:11--
\&
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.21.1\fR 
.if !d from \{\
.ds from \*[segment] 110v:11
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 111r:19
.el .ds to \*[segment] 111r:19
(ff. 110v:11-111r:19)
.print-index-entry title Mh_35:id2301785 .. \n[PN]
.title
Prayer to the Trinity (CP, p. 393 )
./title Mh_35:id2301785###--Mh_35 110v:11--
\&Incipit:
\(lqO helligste mectiste erefwlde oc v atskillige trefoldighed Jeg arme vwerdige syndige men\fIn\fR iske\(rq Explicit:
\(lqoch kome til dyth clareste heme\fIri\fR g\fIis\fR ryge och blyffwe der meth teg ewindelige A m e N\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.21.2\fR 
.if !d from \{\
.ds from \*[segment] 111r:20
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 111v:17
.el .ds to \*[segment] 111v:17
(f. 111r:20-111v.17)
.print-index-entry title Mh_35:id2301834 .. \n[PN]
.title
Prayer to the Trinity (CP, p. 394 )
./title Mh_35:id2301834###--Mh_35 111r:20--
\&Incipit:
\(lqO helligste trefoldighed som er en sand gwd myskwnde teg offw\fIer\fR meg\(rq Explicit:
\(lqoc lad meg see dyth gwdomelig ansicthe i heme\fIri\fR g til ewig thyd ame\fIn\fR\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"Begin msItem
.nr CINDENT (\n[CINDENT]+\n[CINDELTA])
.IP "" \n[CINDENT]u
.\"in \n[CINDENT]
\fB2.4.21.3\fR 
.if !d from \{\
.ds from \*[segment] 111v:18
.ds startsegment \*[segment]
.\}
.ie '\*[startsegment]'\*[segment]' .ds to 112v:3
.el .ds to \*[segment] 112v:3
(ff. 111v:18-112v:3)
.print-index-entry title Mh_35:id2301881 .. \n[PN]
.title
A blessing (CP, p. 394 )
./title Mh_35:id2301881###--Mh_35 111v:18--
\&Incipit:
\(lqUor herres ih\fIes\fR u\fIcristi\fR fred hans sware pines krafft oc macht dygd oc bitth\fIe\fR rhed beware meg\(rq Explicit:
\(lqfra alth vnth nerwerend\fIis\fR framfarend\fIis\fR oc til kome\fIn\fR d\fIis\fR formedelste ih\fIes\fR u cristi mildhed oc baremhartighed AmeN\(rq
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
[\fIMiddelalderens danske Bønnebøger I.
Bind.\fR Karl Martin Nielsen (ed.) Copenhagen.
1946. pp. 155-338 The calendar has not been edited,
but variant readings are given in the apparatus of the edition of Ms.
A 42, Middelalderens danske Bønnebøger.
I. Bind,
pp. 3-14. \fIChristiern Pedersens Danske Skrifter.
Andet Bind.\fR C. J. Brandt & R. Th. Fenger (ed.) Kiøbenhavn.
1851. pp. 393-394]
.nr CINDENT (\n[CINDENT]-\n[CINDELTA])
.\"End msItem
.\"end msContents
.nr CINDENT 0c
.nr PI 0.5c
.SH
.ft R
.smallcaps
Physical description
./smallcaps
.small
.IP "" \n[PI]u
\fBSupport:\fR Parchment.
.IP "" \n[PI]u
\fBExtent:\fR ff.
112
.IP "" \n[PI]u
\fBSize:\fR 185 \(mu 120 mm.
.IP "" \n[PI]u
\fBCollation\fR: 14 quires:
I: 7 (ff. 1-7, first leaf of quire glued to upper cover as pastedown), II: 8 (ff. 8-15), III: 8 (ff. 16-23), IV: 9 (ff. 24-32; f. 31 is added), V: 8 (ff. 33-40), VI: 8 (ff. 41-48), VII: 8 (ff. 49-56), VIII:
8 (ff. 57-64), IX: 8 (ff. 65-72), X: 8 (ff. 73-80), XI: 8 (ff. 81-88), XII: 8 (ff. 89-96), XIII:
8 (ff. 97-104), XIV: 8 (ff. 105-112). One quire missing between f.
56 and 57.
.IP "" \n[PI]u
\fBLayout:\fR One column;
24-26 lines;
written space:
120 x 85 mm.
.IP
\fBScript:\fR The main hand of the manuscript has written the text on ff.
2r-110v in a distinct gothic hybrid.
A younger cursive hand has written the text on ff.
110v-112v .
.big
.SH
.ft I
Decoration
.small
.PP
The original decoration in red ink pen drawing is confined to 28 initials divided in three hierarchical levels or groups.
The decoration is varied only in quantity and everything is undoubtedly executed after the main text and by the scribe himself.
.PP
Style:
The decorative effect is emphasized by the frequent use of void details in the body of the letter and the grid-like disposition of the geometrical or filigranated patterns in the fillings.
The decoration is repeated in Ms.
A 42, Kungliga Biblioteket,
Stockholm ,
and Ms.
A 40, Kungliga Bibliotket,
Stockholm ,
also known as
.print-index-entry title Mh_35:id2302165 .. \n[PN]
.title
\fI
.print-index-entry person Mh_35:id2302171 .. \n[PN]
.person
Ingeborg Predbjørnsdatter
./person Mh_35:id2302171
\& s Tidebog.\fR
./title Mh_35:id2302165 ###--Mh_35 --
.
.PP
The decoration of the 9 initials of the simples kind (ff. 8v , 15v ,
17v , 47v ,
86v , 95v ,
99r , 104r ,
109v) is restricted to white void details of the letter itself and simple geometrical decoration of the area surrounding it,
mostly ca.
5 lines in height.
The initial (I) on f.
8v marks the first hymn of the Matins.
.PP
The 14 initials of medium size (ff. 22r ,
24v , 26r ,
42v , 65r ,
73v , 77r ,
83r , 89v ,
101v ,
102v ,
103r ,
108r) are defined by a slightly larger size,
7-10 lines,
but mainly by the use of extended pen flourishings along parts of the margin.
.XP
The initial (H) on f.
24v marks the first psalm in the Compline
.XP
the initial H on f.
26r marks the beginning of the Seven Penetentiel Psalms
.XP
the Æ on f.
89v initiates the first of the prayers to St Anne.
.PP
The three largest initials are of considerable size,
10 - 15 lines,
with pen flourishes often in two directions framing parts of the written area.
The initials mark major divisions of the text,
the opening of the Little Office of Our Lady (f. 8r ), the opening of the prayer book (f. 33r) and the first prayer to the Virgin (f. 66r ).
.XP
f. 8r Large initial (H) with quadratic and zig zag ornaments left blank,
filling and surrounding area decorated with geometrical and filigranated pattern and filigranated pen flourish borders along left and upper margin.
.XP
f. 33r Large initial (W) with simple ondulated,
floral and heart shaped ornaments left blank,
filling and surrounding area decorated with geometrical pattern and filigranated pen flourish borders along left and upper margin.
.XP
f. 66r Large initial (M) with simple dotted line,
zig zag,
floral and heart shaped ornaments left blank,
filling and surrounding area decorated with geometrical pattern and filigranated pen flourish borders along left and upper margin.
.PP
Two small initials in the added portion on ff.
110v and 111v are different in character,
written in brown ink by the second scribe.
.XP
f. 110v Small initial (O) in brown ink with inscribed human face.
.XP
f. 111v Small initial (U) in brown ink with outspared ondulated and quadratical ornaments.
.PP
One- to two-line red lombards mark the beginning of each period.
.PP
There are pen flourished line-fillers in red.
.PP
The rubrics are written in red ink.
.big
.SH
.ft I
Binding
.small
.PP
Blind-tooled brown calfskin binding,
preserved decorated leather covering,
Denmark contemporary with the manuscript.
Rebinding,
Sweden,
Lund University library bindery,
singed in pencil at the pastedown of lower cover:
Restaurerat av Nils Knutsson 1963 .
Size: 200 x 135 x 45 mm.
.PP
Brown calfskin binding over bevelled wooden boards.
Leather covering from former binding preserved on the new cover.
Two metal hook-clasp fastenings;
lower fastening and engraved hooks from former binding.
Rounded spine.
Tight back with three raised double bands.
Brown blind-tooled library cloth label at the tail of the back.
Embroidered endbands of white linen.
Former edge trimming preserved.
Former endleaves preserved as separate pastedowns.
Single flyleaf of parchment at the front,
the upper half of the leaf missing.
All along sewing on three raised cords.
.PP
The covers are blind-tooled with a triple fillets frame and divided in six double line fillet compartments.
The compartments of the upper cover are decorated with stamps of animal and symbolic motifs:
the Y-shaped foliated cross,
a quadrangle griffin,
a burning heart,
a bird with forked tail and an eagle,
and the lower cover compartments only with a repeated burning heart and eagle.
.big
.SH
.ft I
Foliation
.small
.PP
Foliated in ink in upper right corner by modern cataloguer.
.big
.SH
.ft I
Condition
.small
.PP
The first leaf of the manuscript has been cut.
Lacuna between f.
56 and f.
57 (after 7th quire).
.big
.SH
.ft R
.smallcaps
History
./smallcaps
.small
.big
.SH
.ft I
Origin
.small
.PP
Karen Ludvigsdatter's prayer book was written in
.print-index-entry place Mh_35:id2302571 .. \n[PN]
.place
Jutland
./place Mh_35:id2302571
\& around 1500 .
The language cannot be caracterized as Jutland dialect,
though it shows certain Jutland regional features according to
.print-index-entry person Mh_35:id2302584 .. \n[PN]
.person
Karl Martin Nielsen
./person Mh_35:id2302584
\&. Two other Danish books of hours show a similar Jutlandish orthography;
they were possibly produced in the same scriptorium:
Ms. A 42,
Kungliga Biblioteket,
Stockholm ,
and Ms.
A 40, Kungliga Bibliotket,
Stockholm .
.PP
.print-index-entry person Mh_35:id2302605 .. \n[PN]
.person
Karen Ludvigsdatter Rosenkrantz
./person Mh_35:id2302605
\& was the daughter of
.print-index-entry person Mh_35:id2302615 .. \n[PN]
.person
Ludvig Nielsen Rosenkrantz
./person Mh_35:id2302615
\&, a member of the Danish Rigsråd (c. 1492), and
.print-index-entry person Mh_35:id2302624 .. \n[PN]
.person
Kirsten Andersdatter Hak
./person Mh_35:id2302624
\& (fl. 1492). Karen was married to the High Court judge and member of the Rigsråd
.print-index-entry person Mh_35:id2302633 .. \n[PN]
.person
Mogens Munk
./person Mh_35:id2302633
\& (c. 1558 ), a brother of the bishop of
.print-index-entry place Mh_35:id2302644 .. \n[PN]
.place
Ribe
./place Mh_35:id2302644
\&
.print-index-entry person Mh_35:id2302651 .. \n[PN]
.person
Iver Munk
./person Mh_35:id2302651
\&. She died in 1535 and was buried at
.print-index-entry name Mh_35:id2302661 .. \n[PN]
.name
Viborg Cathedral
./name Mh_35:id2302661
\&. The owner's name is mentioned in a prayer to Jesus Christ on f.
50r : thin vuærdugæ thienistæ qwi\fIn\fR næ karine lodwigs dottær .
.PP
On f.
1v someone wrote the genealogy on her father's side:
.print-index-entry person Mh_35:id2302690 .. \n[PN]
.person
Ivar
./person Mh_35:id2302690
\&,
.print-index-entry person Mh_35:id2302697 .. \n[PN]
.person
Marsk Iverssen
./person Mh_35:id2302697
\&,
.print-index-entry person Mh_35:id2302703 .. \n[PN]
.person
Albert Iversson Marsksson
./person Mh_35:id2302703
\&,
.print-index-entry person Mh_35:id2302720 .. \n[PN]
.person
Ivar Albertsson
./person Mh_35:id2302720
\&,
.print-index-entry person Mh_35:id2302726 .. \n[PN]
.person
Jens Iversson
./person Mh_35:id2302726
\&,
.print-index-entry person Mh_35:id2302733 .. \n[PN]
.person
Niels Jensson
./person Mh_35:id2302733
\& (c. around 1412),
.print-index-entry person Mh_35:id2302740 .. \n[PN]
.person
Ludvig Nielsson
./person Mh_35:id2302740
\&. The same names appear in an older hand (gothic cursive) on the back pastedown:
Her iuer Her marssk iuerssen Her albret iuerssen marssk Her iuer albretss\fIen\fR iuerssen Her iens iuerssen Her niels iuerssen Her loduich nielssen .
.big
.SH
.ft I
Provenance
.small
.PP
Medeltidshandskrift 35 was owned by
.print-index-entry person Mh_35:id2302781 .. \n[PN]
.person
Erik Joh.
Meck
./person Mh_35:id2302781
\& at the end of the 17th century.
It was probably left to him by his father-in-law
.print-index-entry person Mh_35:id2302791 .. \n[PN]
.person
Magnus Durell
./person Mh_35:id2302791
\&.
.big
.SH
.ft I
Acquisition
.small
.PP
Acquired in 1704 when the Lund University Library purchased the
.print-index-entry person Mh_35:id2302812 .. \n[PN]
.person
Meck
./person Mh_35:id2302812
\& book collection.
.big
.SH
.ft R
.smallcaps
Bibliography
./smallcaps
.small
.XP
.print-index-entry author Mh_35:id2302942 .. \n[PN]
Nielsen,
Lauritz:
.author-index Nielsen, Lauritz
\fIDanmarks middelalderlige Haandskrifter.\fR København.
1937. p. 144.
.XP
.print-index-entry author Mh_35:id2302976 .. \n[PN]
Otto,
Alfred:
.author-index Otto, Alfred
Indledning.
\fIMiddelalderens danske Bønnebøger.\fR Copenhagen.
1946. p. XXIII.
.XP
.print-index-entry author Mh_35:id2303016 .. \n[PN]
Nielsen,
Karl Martin:
.author-index Nielsen, Karl Martin
Haandskrifter.
\fIMiddelalderens danske Bønnebøger.
V. Bind.
Kommentar og Registre.\fR København.
1982. pp. 18-19.
.XP
.print-index-entry author Mh_35:id2303059 .. \n[PN]
Nielsen,
Karl Martin:
.author-index Nielsen, Karl Martin
Tre jyske bønnebøger.
\fIFestskrift til Peter Skautrup.\fR Århus.
1956. pp. 223-238.
.XP
.print-index-entry author Mh_35:id2303100 .. \n[PN]
Dahlerup,
Pil:
.author-index Dahlerup, Pil
Den signede dag.
\fILiv og Lyst.
Artikler og essays.\fR København.
1987. pp. 9-34.
.XP
.print-index-entry author Mh_35:id2303140 .. \n[PN]
Frederiksen,
Britta Olrik:
.author-index Frederiksen, Britta Olrik
Til diskussion om den middelalderlige dagvises jordiske hjemsted og himmelske ophav.
\fIDanske studier 1988.\fR 1988.
83 pp.
5-31.
.XP
.print-index-entry author Mh_35:id2303184 .. \n[PN]
Dahlerup,
Pil:
.author-index Dahlerup, Pil
 \fI Dansk Litteratur. Middelalder. 1. Religiøs litteratur.\fR Copenhagen. 1998.   pp. 127, 129, 464-465.  p. 29 (on Psalm 8), p. 127 (on Psalm 101/102/103?), pp. 464-465 (Prayer to Jesus Christ/Dagvisen)
