T{
.na
900\(en925
T}#Medeltidshandskrift 1#1
_
T{
.na
1025\(en1075
T}#Medeltidshandskrift 54#165
_
T{
.na
1130\(en1418
T}#Medeltidshandskrift 7#24
_
T{
.na
1120\(en1525
T}#Medeltidshandskrift 6#15
_
T{
.na
1100\(en1125
T}#Medeltidshandskrift 2#5
_
T{
.na
1150\(en1200
T}#Medeltidshandskrift 3#8
_
T{
.na
1150\(en1200
T}#Medeltidshandskrift 4#10
_
T{
.na
1130\(en1170
T}#Medeltidshandskrift 5#12
_
T{
.na
1200\(en1400
T}#Medeltidshandskrift 12#36
_
T{
.na
1204\(en1205
T}#Medeltidshandskrift 58#178
_
T{
.na
1240\(en1260
T}#Medeltidshandskrift 11#34
_
T{
.na
1275\(en1300
T}#Medeltidshandskrift 10#33
_
T{
.na
1200\(en1225
T}#Medeltidshandskrift 60#183
_
T{
.na
1275\(en1300
T}#Medeltidshandskrift 9#30
_
T{
.na
1180\(en1300
T}#Medeltidshandskrift 50#155
_
T{
.na
1300\(en1500
T}#Medeltidshandskrift 16#41
_
T{
.na
1320\(en1500
T}#Medeltidshandskrift 13#37
_
T{
.na
1300\(en1499
T}#Medeltidshandskrift 14#39
_
T{
.na
1300\(en1400
T}#Medeltidshandskrift 18#46
_
T{
.na
1305\(en1315
T}#Medeltidshandskrift 15#40
_
T{
.na
1300\(en1330
T}#Medeltidshandskrift 55#168
_
T{
.na
1300\(en1400
T}#Medeltidshandskrift 45#147
_
T{
.na
1390\(en1400
T}#Deposition 1#194
_
T{
.na
1380\(en1425
T}#Medeltidshandskrift 19#49
_
T{
.na
1347\(en1400
T}#Medeltidshandskrift 17#43
_
T{
.na
1350\(en1370
T}#Medeltidshandskrift 57#174
_
T{
.na
1400\(en1500
T}#Medeltidshandskrift 32b#90
_
T{
.na
1400\(en1500
T}#Medeltidshandskrift 42#137
_
T{
.na
1400\(en1500
T}#Medeltidshandskrift 44#146
_
T{
.na
1400\(en1500
T}#Medeltidshandskrift 53#164
_
T{
.na
1400\(en1500
T}#Medeltidshandskrift 65#192
_
T{
.na
1400\(en1500
T}#Medeltidshandskrift 8#28
_
T{
.na
1444\(en1444
T}#Medeltidshandskrift 48#151
_
T{
.na
1460\(en1480
T}#Medeltidshandskrift 27#72
_
T{
.na
1460\(en1480
T}#Medeltidshandskrift 32a#85
_
T{
.na
1475\(en1500
T}#Medeltidshandskrift 32#83
_
T{
.na
1400\(en1446
T}#Medeltidshandskrift 21#55
_
T{
.na
1475\(en1500
T}#Medeltidshandskrift 34#96
_
T{
.na
1400\(en1450
T}#Medeltidshandskrift 20#52
_
T{
.na
1400\(en1450
T}#Medeltidshandskrift 31#82
_
T{
.na
1475\(en1500
T}#Medeltidshandskrift 51#156
_
T{
.na
1480\(en1520
T}#Medeltidshandskrift 49#153
_
T{
.na
1475\(en1600
T}#Medeltidshandskrift 30#81
_
T{
.na
1475\(en1525
T}#Medeltidshandskrift 47#149
_
T{
.na
1475\(en1550
T}#Medeltidshandskrift 59#181
_
T{
.na
1450\(en1500
T}#Medeltidshandskrift 38#124
_
T{
.na
1450\(en1500
T}#Medeltidshandskrift 63#188
_
T{
.na
1454\(en1477
T}#Medeltidshandskrift 62#186
_
T{
.na
1460\(en1480
T}#Medeltidshandskrift 52#158
_
T{
.na
1440\(en1455
T}#Medeltidshandskrift 24#64
_
T{
.na
1440\(en1460
T}#Medeltidshandskrift 26#71
_
T{
.na
1450\(en1500
T}#Medeltidshandskrift 28#77
_
T{
.na
1450\(en1500
T}#Medeltidshandskrift 29#78
_
T{
.na
1450\(en1500
T}#Medeltidshandskrift 41#133
_
T{
.na
1450\(en1500
T}#Medeltidshandskrift 64#190
_
T{
.na
1425\(en1550
T}#Medeltidshandskrift 23#60
_
T{
.na
1457\(en1550
T}#Medeltidshandskrift 25#67
_
T{
.na
1490\(en1510
T}#Medeltidshandskrift 35#99
_
T{
.na
1500\(en1600
T}#Medeltidshandskrift 43b#145
_
T{
.na
1507\(en1507
T}#Medeltidshandskrift 56#170
_
T{
.na
1535\(en1535
T}#Medeltidshandskrift 36#119
_
T{
.na
1538\(en1538
T}#Medeltidshandskrift 61#185
_
T{
.na
1500\(en1525
T}#Medeltidshandskrift 33#92
_
T{
.na
1500\(en1550
T}#Medeltidshandskrift 46#148
_
T{
.na
1500\(en1546
T}#Medeltidshandskrift 37#121
_
T{
.na
1490\(en1522
T}#Medeltidshandskrift 43a#142
_
T{
.na
1500\(en1530
T}#Medeltidshandskrift 43#139
_
T{
.na
1550\(en1575
T}#Medeltidshandskrift 39#126
_
T{
.na
1650\(en1700
T}#Medeltidshandskrift 40#131
_
