.XP
A. Siemaszko, 163
.XP
Blosius Palladius, 185
.XP
Chara Suoellin, 163
.XP
Jean Fouquet, 124
.XP
Jeremiah, 125
.XP
Johan Gabriel Banér, 75
.XP
Johan Klasson Banér, 75
.XP
Joseph Siemaszko, 163
.XP
karine lodwigs dottær, 106
.XP
Viborg Cathedral, 118
.XP
Κόδρας, 175
.XP
Ἀλφιός, 175
.XP
μηχαελ, 177
.XP
Ἐπίμαχος καὶ Γορδιανός, 175
.XP
Σίμων ὁ ζηλωτής, 175
.XP
Τιμόθεος ὁ πατριάρχης, 175
.XP
Τρυφαίνη, 175
.XP
Φιλάδελφος καὶ Κυρῖνος, 175
.XP
Χρηστοφόρος, 175
